### ISSUE TITLE
Direct the library links to player's server and add version params

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#1030]
As it is now, all the assets comes from Tawitawi server. This means we'll have to redownload the assets all over again.
Also, pls add version numbers to the swf links.

![plsfix](https://cloud.githubusercontent.com/assets/12930396/11173267/d5bea1da-8c4e-11e5-9b3b-601c33e84777.png)

**Comment by dragonjet** [comment]
server IP is possible, but version number will need more twists to be able to attach it to the link

**Comment by LostLogia4** [comment]
more twists? why? :open_mouth:

**Comment by dragonjet** [comment]
since version numbers are coming from `api_start2` we'll also need to record them in localStorage, whereas server IP is already in the player data

**Comment by dragonjet** [comment]
hm, I think the best way to go about this is to save the full master on localStorage. right now we are only saving ships and items. since the master file is not that large anymore, the option is now open for us to save it.

once we do, we can easily pull in version numbers. so it might be better to open a new thread for the saving of full master

**Comment by LostLogia4** [comment]
okay then, future comments will be covered in #1157

**Comment by dragonjet** [comment]
Merged #1172 to `master`. api_version now possible

**Comment by LostLogia4** [comment]
Moved the goalpost of this issue to implementation of version params.

**Comment by LostLogia4** [comment]
Already implemented, closing.
First of SR milestone plans, fulfilled.
