### ISSUE TITLE
Multiple Tabs in Strategy Room.

### ISSUE THREAD

**Issue by Comett** [KC3Kai/KC3Kai#1068]
There are some tabs in the strategy room that don't load and goes unresponsive in which I have to close the tab and re-open the strategy room if I want to access other things. 

Quick video of the problem: http://comett.cguy.me/MWBCv.mp4

I tried reinstalling the extension, and before my account was "registered" to the strategy room everything would load fine, but when it picked up my account, it would happen again.

**Comment by Comett** [comment]
Fixed. Not sure how but if it was your doing thanks!

**Comment by ethrundr** [comment]
It's great that you find your problem solved. However, in case there are error occurs to other user out there, here's some simple guide for "KC3Kai-DIY-Troubleshooting". Hope this may helps.


First Method: Restart the Extension.

1. Open `chrome://extensions`.
2. Enable the "Developer Mode" by ticking box beside it, then hit Ctrl+R to force-reload all of your extensions.
3. Wait until it is reloaded (it usually only takes at most 1-2 minutes, but for safety, let's wait for 2-3 minutes). All tabs related to the extension should be closed upon reloading.
4. After you confirm that the extension has been reloaded, relaunch all the extension-tabs you want to use (Frame/API play, Strategy Room, Admiral Panel, etc)
5. See if this fix the problem. If not, then we're entering the second method.


Second Method: Restart the Extension and the Chrome.

1. Do this step only if you unable to fix the problem from first method.
2. Repeat steps 1 to 3 on the first method.
3. However, different from the first method, now after reload completes, you'll need to reload your browser. Save all your works on the Chrome (posts, emails, etc), then completely close all your browser. It is usually takes up to 10 minutes for Chrome to completely terminates all its services in case you're running multiple windows, tabs and extensions at once. Depending to your setup, it may restore all the previous opened tabs upon relaunching. Thus it is required to ensure no KC3kai tabs or features are opened/active.
4. Confirm that all services under Chrome has terminated. You may do so by opening Task Manager or Activity Monitor, and check there is no either "Google Chrome" or "Google Chrome Helper" left. If there any of these left, right-click each of them and choose "End Process" or "Quit".
5. After confirm that all service has terminated, launch your Chrome once again.
6. Reopen the KC3kai tabs as you needed.
7. Confirm whether it fixed the bug. If not, we'll continue to the third, and last method.


Third Method: Re-installing.
_**Warning**: This step **MIGHT** erase all of your data recorded in KC3kai. Keep this method as last resort when everything is already done and brings no result._

1. Open `chrome://extensions`, then enable the Developer Mode.
2. Click the "Update Extensions" to check whether your extensions is missing the latest update. If there are missed updates, the extension will then updating and reloading itself. Thus, stop this method after completion and check whether the problem is fixed or not. If the problem persist, then you may continue.
3. After updating and if there is no update or the problem persist after update, do the clean re-install.
4. Still on the "Developer Mode enabled", click the trash can symbol to completely delete the extension. Click OK on the confirmation window to perform removal.
5. Relaunch your Chrome to complete the removal.
6. After reopening the Chrome, go to Webstore and re-add the extensions to your Chrome.
7. Check if problem persist. If still persist, you may do one of these: 
   * Check for Chrome issues or updates. One of these issues might be happening in your Chrome, thus rendering the extensions inoperable. You may also try to clean re-install your Chrome if reinstalling the extension and updating the Chrome won't fix the problem.
   * Contact us here with the explanation on what happening. If you have screenshots, it might be better. There are chances that these issues are generated by our mistakes, especially when you are using the GitHub Developer Build instead of the Public Webstore build.
   * Check your memory allocation and PC usage. Although KC3kai not consume that much memory, high PC or memory usage may render some of our feature lagging or not working at all, due to resource shortage. Closing unused application or background services might solve the issue. However, take utmost care while closing services. Your PC may suddenly running wild if you close the wrong services.
   * In some rare cases, restarting your whole system might help to fix the error. This especially true when you've met with memory shortage issue some time before the KC3kai issue occurs. I personally advise to try restarting your whole system before reinstalling.

**Comment by dragonjet** [comment]
oh wow I didn't know about <kbd>Ctrl</kbd>+<kbd>R</kbd>
