### ISSUE TITLE
Resource History and Sortie History cannot be updated if 航海日誌 拡張版 is enabled

### ISSUE THREAD

**Issue by OniityanH** [KC3Kai/KC3Kai#1074]
![qq 20151129141239](https://cloud.githubusercontent.com/assets/16058403/11455636/5e3e072c-96a3-11e5-85d0-b7b3d91511ac.jpg)
![qq 20151129141310](https://cloud.githubusercontent.com/assets/16058403/11455637/5e41f63e-96a3-11e5-88da-79cdc4d39bd0.jpg)
![qq 20151129141229](https://cloud.githubusercontent.com/assets/16058403/11455662/809be1b2-96a4-11e5-9be7-e8b5441e0c4d.jpg)

i know it may not your problem, i just want to ask could you fix that problem if it is not really hard to solve? coz i used  the 航海日誌 拡張版 for a whole year. i can't abandon it really.

P.S. the link for 航海日誌 拡張版
http://nekopanda.blog.jp/

**Comment by Crazyteitoku** [comment]
I do believe this has to do with how you setup your proxy server. I have both KC3 Kai running along with MyFleetGirls and Logbook, they are all working fine.

Mind if you disclose how is your proxy server setup?

**Comment by OniityanH** [comment]
thanks mate, i think the problem should be Shimakaze go, sorry i didn't mention that, there are the settings for both  航海日誌 and Shimakaze go.

![qq 20151129210301](https://cloud.githubusercontent.com/assets/16058403/11457169/f24ced96-96dc-11e5-88ee-cf6f16e71e93.jpg)
![qq 20151129210307](https://cloud.githubusercontent.com/assets/16058403/11457167/f1e99f48-96dc-11e5-9e58-182a0684eecd.jpg)
![qq 20151129210328](https://cloud.githubusercontent.com/assets/16058403/11457168/f2164944-96dc-11e5-999c-1176e8b1aa24.jpg)

**Comment by NicolaosGreene** [comment]
I remember seeing something about Shimakaze go stealing the packets or some such and I think it is not supported with KC3kai am but I am not sure.

**Comment by Crazyteitoku** [comment]
ShimakazeGO pretty much doesn't send server timestamp that is normally provided by Kadokawa servers. We had a discussion about this awhile ago in [here](https://github.com/KC3Kai/KC3Kai/issues/868) followed by a closed feature request [here](https://github.com/KC3Kai/KC3Kai/issues/880).

Awhile back it was stated that we do not support nor condone the use of KC3 Kai with some other software which modifies player data simply because of a ban risk which:
- leaves the user generally wanting to put blame on everything that is involved with one's session and/or,  
- leaves questions unanswered in the reasons as to why they were banned but with a few clues that they were using other (one or more) software but didn't mention the rest which leaves readers/observers to speculate that the ban could only be the result from one of the softwares/tools the user has used.

I can point to you an example, player uses a viewer (KCV, KC3 Kai, KCT), player then repeatedly spams F5 and gets banned as a subsequent result due to putting a burden on KC servers. Players gets banned and moans about it publicly but stated that they use a viewer. The public then speculates wrongly that the viewers that were the culprit.

Another example for a different outcome, a player users a viewer (KCV, KC3 Kai, KCT), player then chains a whole bunch of other tools to go along with it such as (but are not included to), logbook, myfleetgirls, shimakazeGo, etc. Player all of the sudden gets banned but has been bragging screenshots before with the use of various tools other than say for instance shimakazeGo. The player or the public then speculates out of all those other screenshots provided other than shimakazeGo, other tools becomes scapegoat and that shimakazeGo is guilt-free simply because the player either omitted the inclusion of that info or has indirectly implied others.

This is a real headache from any third party Kancolle tools developers and their respective groups simply because they have to openly disclose the fact that they're not liable for any loss for the player upon the use of the software but also potentially not support the use of other tools that they do not condone either by not making a guide and/or to implicitly allow that. Even for KC3 Kai alone there is always a question about players fearful of using anything that seems to "enhance" their gameplay. This was the reason why @dragonjet added an option to "Play on DMM website" which was basically for those not wishing to use KC3 Kai as a viewer but as a means to get into the game itself without having to deal with cookies and/or be fearful of getting banned as the result of using KC3 Kai.

Mind you in 2014 there was a large ban scare because of a viewer that had options which supposedly speeds up the player's gameplay (and that was illegal obviously). The player(s) were banned and then a great deal of FUD spread around viewers making them unpopular in general because of the fact that users are prone to being banned. Virtually everyone has their opinions as well as their stances on such cases.

Now, as of recent, we sort of have [a new discussion](https://github.com/KC3Kai/KC3Kai/issues/1065) about getting KC3 Kai to only work with shimakazeGo. I am uncertain whether or not will such thoughts be taken into action. However the point was (and still most likely is) that we do not openly condone nor offer much support for any users wishing to "stack" one or more tools on top of their KC3 Kai.

By "tools" definition, I mean it could range anything from (but are not limited to): 
- KCV, KCT, EO, etc
- logbook, myfleetgirls, etc.
- shimakazeGo, ooicacher, kancollecacher, etc.

Now that we have these information out of the way. I want to point on a case of a possibility to allow these other "tools" to work together but it **does not** mean that I am willing to offer support **nor** would I really condone such actions. @nagatoyk pointed out the use of SwitchyOmega (formerly known as SwitchySharp) to allow data from the browser to be passed onto a proxy server. I have a similar idea with what @nagatoyk mentioned except I have my KC3 Kai working with both myfleetgirls and logbook. You could probably use the same extension (SwitchyOmega) to "daisy chain" your proxies. In theory, data from KC is first sent to KC3 Kai before it is passed on via the extension to some other proxy of choice.

Again, I **do not** and **will not** openly condone nor support whatever actions you decide to choose. You are therefore liable for any actions that may subsequently result in you from being banned from Kancolle but are to shoulder that burden onto yourself.

**Comment by ethrundr** [comment]
Agreed with @Crazyteitoku.

To support his opinion, let me give some real-case situation, which really happens quite some time ago:

There are banning "festival" back on April last year. Not less than a thousand players are banned from the game due to various reason. At that time, there are three major third-party tools that are widely used: KC!T (later known as KC3, predecessor of KC3kai), KCV and KCT, and other tools.

One of those tools at that time is suspected (later, proved) to be sending synthetic API calls to the server, causing confusion to the server (even though in the end the server still able to respond correctly), which this undoubtedly causing some excess burden to the server. Subsequently, most of the user of this tool is getting banned one by one. 

However, most of them are not disclosing the tool they are using, or only disclose a few (several of them are using multiple tools at once). As the result, whole third-party applications exist at that time, including those who actually are safe, are being blacklisted and lost serious amount of users and active contributor. Due to this major blow, most of the third-party application that still survive the blow has sworn not to include any ban-potential feature at any cost.

This is the main reason, as well as one of the background, why we on KC3kai (either personally per member or as a whole team) *will not* support any feature that has high risk of being banned.

**Comment by Crazyteitoku** [comment]
I am locking this thread as:
- the OP has no further questions on this matter.
- we do not want any further discussions about how one does go about proxy chaining KC3 Kai to other tools. 
- the hints has already been provided as well as our stances on tools that involves altering game data has already been stated.
- this issue was basically off-topic from the beginning. To make matters worse we have had a recent case involving one wanting to use shimakazeGo with KC3 Kai.
- we do not really openly condone using more than one viewer on top of your average KanColle session. 

I am probably one of the few who chains more than one tool on top of KC3 Kai but none of these are able to directly manipulate player's data (unlike shimakazeGo). Other than that I know full well that should I get banned because I have too many tools running on my end, it will be ultimately my own fault and not the fault of others.

**Case closed.**

**Comment by Crazyteitoku** [comment]
Correcting my stance on this, we do offer very minimal support to those who use ShimakazeGo (Island wind, 島風Go, etc) but you are to proceed these at your own expense/risk.
