### ISSUE TITLE
Hard to connect to KanColle

### ISSUE THREAD

**Issue by tdtv-bkt432** [KC3Kai/KC3Kai#1341]
After new KC update,
Catbomb was very often when connect to KC and frozen at loading screen (load very very long).
[http://i.imgur.com/wfCqVxs.png](url)

**Comment by LostLogia4** [comment]
I personally doubt this has anything to do with KC3. What makes you think so anyway?

**Comment by tdtv-bkt432** [comment]
Kinda
without KC3: Server -> Cilent.
with KC3: Server -> KC3 -> Cilent. <(")

**Comment by dragonjet** [comment]
we are never in between the server and the client. As I have said countless times, we only read Chrome network history, the reason why we need your F12 panel open. Click on the Network tab instead of KanColle tab in the panel. You'll see your network history, that's what we read. We don't even have a middleman proxy unlike all other viewers. We are 100% NO network layer.
```
Server <---> Client
           | Chrome --> KC3
```
