### ISSUE TITLE
[Suggestion] Disable annoying taiha alert on top screen when screenshotting

### ISSUE THREAD

**Issue by tayuku** [KC3Kai/KC3Kai#1365]
Hiya! I don't know if this feature is fully supported or important. 

Is there a way to disable the top portion of the annoying taiha alert?
Maybe there's another option to only have the sound effect and bottom part flashing?

Thanks a lot!

**Comment by dragonjet** [comment]
ah there's no feature like that yet, but we can add it

**Comment by rephira** [comment]
@dragonjet I suggest that we change this further and make an option where the taiha alert shows up only on the dev tool and not the game screen.

Some people use KC3kai and like the fact that there is an alert, but says that when they are doing live streaming, it can get in the way.

**Comment by DLRevan** [comment]
Can I suggest a few more things if the aim is to improve this function in the future?

There can be options to mute and turn off the overlays in the dev tool area, just like there is a mute sound button. To reduce the chance of user forgetting its off, the dev tool could still flash.

Also, right now the alert triggers when going into night battle if ship became taiha in day during on the same node because hp updates again when player clicks night battle. I think it would be better if a check is made so that it only triggers after battle result.

**Comment by dragonjet** [comment]
Fixed in #1424

for @DLRevan's additional suggestions, please create a new issue.
thanks :+1:
