### ISSUE TITLE
Wrong Akashi Timer in the main panel

### ISSUE THREAD

**Issue by Kirayao** [KC3Kai/KC3Kai#1378]
In the current setting, Akashi timer in the main panel would reset every time you go back and forth to the lobby. However, this is not correct since the timer won't reset if you don't change the fleet. This bug makes the Akashi timer totally useless since it will always give you wrong count on the time.

**Comment by rephira** [comment]
We will be looking into the details about the Akashi repair mechanism. 

https://gist.github.com/fujieda/440fa64d310c2b6960f3

I think this site might be able to give us some insight.

**Comment by nonsensed** [comment]
If it counts for anything, I just confirmed in-game that it's true. If you keep flipping back to the main screen, it won't reset the timer. After 20 minutes, everyone still regenerated 1 HP.

**Comment by rephira** [comment]
Yup I confirmed it myself as well. So, we need to find the constraints on what interrupts the timer clearly. So far just going back and forth between port screen is not the reset factor.

We know for sure that when ships don't change the counter continues to tick without interruption, so we should probably implement at least that part.

**Comment by rephira** [comment]
So far, from what I can observe, I think the interrupt happens when there is a specific change in the fleet which requires "recalculations",

For example, when you **change fleet comp by adding or removing ships**, it probably redoes all of the calculation, figuring out if the added ship is within Akashi's repair range and if so, if the ship being added or removed can actually be repaired by Akashi. After calculating that, it restarts the repair.

It also will redo the calculation even when the fleet does not change **if there is a tick that is stored that is ready to go off**. When you come back to port with a repair tick, it will immediately add the amount to the kanmusus' HP. This means that now the calculation for the repair time has to be done again. (Because the amount of time needed for 1 tick AFTER the first tick will vary depending on the remaining HP. I can prove this mathematically) I think in broader application, it will probably work in the same way when an Akashi fleet goes into a sortie and a ship within the fleet gets damaged.

**Comment by rephira** [comment]
Also, when removing or adding ships with the ticks already counted, **all the ticks will become nullified, and counter will restart with 0 ticks.**

**Comment by Kirayao** [comment]
AFAIK, the Akashi timer only reset when you change the fleet or get skipped if you bring the fleet out for battle (Yes, Akashi as the flagship). Otherwise, the timer would continue to tick.

**Comment by rephira** [comment]
It definitely resets when Akashi repair has HP to repair. This is because of Akashi's repair mechanism.

http://kancolle.wikia.com/wiki/Docking
Using this as a reference for calculating repair time

Let's say we have a Yamato Lv40, who lost 5HP

Originally the amount of time it would take for Yamato's repair would be 5*2*5:00+0:30 which is 50 minutes and 30 seconds. Since docking and Akashi repair takes exactly the same time to repair to full HP, the amount of time needed for repair would be calculated as follows.

It takes at least 20 min for Akashi to repair the starting 1 HP, the remaining 4 HP will be repaired over 50:30-20:00=30:30.
Subsequently, time to repair 1 HP would be 30:30/4 = approximately 7:28.

Now let's say you come back to port after enough time has passed to repair 2 HP. Yamato will now have only 3 HP to repair with the 2 HP repair being replied to her. This means Yamato's repair time will now be recalculated. 

3*2*5:00+0:30=30:30 will be needed.
Again, we need 20 minutes to repair starting 1 HP
Means that 2 HP will be recovered over 30:30-20:00=10:30.
10:30/2 = 5:15 will be needed per HP.

So, just by knowing that the amount of time needed per HP repair changes, we should assume that the timer is completely reset when there is any HP repair that occurs.

**Comment by dragonjet** [comment]
I'm sorry @rephira I was not able to follow you on the math and mechanics, is there something we need to fix on kc3 side? XD

**Comment by Kirayao** [comment]
The countdown timer shown when you move the mouse on the ship repairing by Akashi is wrong.
rephira and I were discussing the mechanism of Akashi. It should only be reset when you change the fleet or any ship that is repairing by Akashi gained HP. 
In the current code, it is reset every time you go back and forth in the lobby, which is absolutely wrong.

**Comment by dragonjet** [comment]
got it, it's a regression. I wonder what causes this. I can take a look during weekends but if anyone can catch this sooner, that would be nice

**Comment by rephira** [comment]
@dragonjet just taking a quick look. Would it be possible to alleviate this issue by maybe adding a checking mechanism somewhere?

We would only need to check one thing when you return to port screen. I see that the repair resets properly when ships are being switched in and out. The only thing we need to check is to see if a single repair tick has occurred.

In other words, we just need to check if 20 minutes has passed since the last fleet comp change with Akashi as flagship.

If the wording sounds weird, let me know.

**Comment by dragonjet** [comment]
tbh im not sure, can someone take a look? :sweat_smile:

**Comment by rephira** [comment]
@dragonjet I think I might have found the issue, thx to @ReiFan49 for the help.

It seems like the setup on portRefresh under PlayerManager.js was forcing the reset every single time the player returned to port page because it was set up so that `fleet.checkAkashi(true)`

This might have been due to the fact that we had misinformation when we were first designing the Akashi timer, where it was believed that returning to port would reset the timer all the time. (The fact which has been debunked for awhile, without our realization O_O)

Now, we know that this is not the case, so I think just removing the `true` argument here would solve the issue. I have tested out the changes using the dev build, and got the result that was expected if the function was working properly (not resetting when there is 0 ticks, resetting when there is 1 or more ticks)

**Comment by dragonjet** [comment]
thanks for the info, added to 30.4.0 as requested

**Comment by Javran** [comment]
I notice when I go back to port with 1 tick accumulated, HP does get recovered as expected but the timer is reset to something around 17 mins rather than 20 mins and all following times seem to offset:
right before the ~17 min marker come down:
![2016-07-02_131855_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/16538502/b20d56dc-4058-11e6-95f9-76da1ffbe023.jpg)

and after:

![2016-07-02_131956_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/16538504/b98dd738-4058-11e6-9909-7f27fda93a67.jpg)

this time (above) it does reset to 20 mins, but the HP wasn't recovered.

and after ~3 mins past, the HP recovery happened:
![2016-07-02_132329_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/16538506/bf085904-4058-11e6-9446-054002008a4e.jpg)

time of taking these screenshots:
![2016-07-02_132504_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/16538508/c55c6eee-4058-11e6-9721-ab07afcabfd4.jpg)

reopening this because I think it is the same issue.

**Comment by rephira** [comment]
Have you checked if the offset actually holds or not?

**Comment by Javran** [comment]
@rephira what do you mean about "offset holds or not"?

**Comment by dragonjet** [comment]
how come there's an akashi repair time of 54 mins? isn't it every 20 minute tick?

**Comment by Javran** [comment]
bumping this issue. having a wrong akashi timer for such a long time starts to annoy me.

If I understand the mechanism correctly, whenever akashi repair applies (which means ships' HP are recovered at that very moment), the akashi tick resets to 0 and we should reset timer to exactly 20 mins.

however in the current version after the repair is applied, the timer always reset to a time less than 20 mins - so it is always wrong after the first repair is applied until next time fleet compo changes.
