### ISSUE TITLE
Ship face not shown even if there's a drop

### ISSUE THREAD

**Issue by ForteGigas** [KC3Kai/KC3Kai#1379]
After clearing E-2 Easy Node K, Yuugumo dropped but the viewer showed that nothing dropped.

https://www.dropbox.com/s/is1q08d6hlp2j9x/bug.jpg?dl=0

**Comment by rephira** [comment]
http://imgur.com/laT9ULa

**Comment by dragonjet** [comment]
the only way I could think this would happen is that "ship drop faces" on settings is disabled. can you guys check?

**Comment by rephira** [comment]
I checked, and this was a bug. Now that the event is over I dunno if it will be repeatable but I know that the ships from all the other node was showing drops just fine.

I also found that this bug seems to happen only on the boss node of each map. (had it happen on E-3 boss and E-4 boss), iirc, E-2J as mentioned above is also a boss node. (It couldn't be K because K is an off-route node)

So at this point, I think it was probably a bug that was related to all the boss nodes. We'll see when the next even comes around and see if the bug persists.

**Comment by dragonjet** [comment]
true, might be something connected to, when boss node victory, the drop variable might have become an array or something since you'll be getting reward ships or a similar effect. we can observe next event, but for now we can close this since next one might still be 3 months away
