### ISSUE TITLE
Ship Library problems.

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1381]
in the lastest master branch: https://github.com/KC3Kai/KC3Kai/commit/6128991473c4ff0c2cf709ee4b30a1d4ae4285a1

wrong object layout:

![2016-05-18_105110_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/15363358/7f8f7112-1ce6-11e6-8033-35279efac3f1.jpg)

also I find in this commit click on a ship also moves that entity to the top of the list, is it possible to disable this?

**Comment by Javran** [comment]
Equipment library has the same problem. unless jumping from other tabs, I think list should not try to scroll itself and relying on auto reloading mechanism means `execute` will be executed every time you click on a different ship, causing list state to be reset and cannot remember previous position.

**Comment by sinsinpub** [comment]
oh the layout is fixed. and the 'ship list scrolling' is not on that commit.

i don't understand the 'scrolling issue' u described. the reason of adding this is just because the ship list always reset to the first element, never 'remember its position' (coz it's rebuilt from scratch). so each time when a ship showed at right panel, have the left entity scroll to the top to match with right.
u can try to disable that code snippet to see what happen (located at `mstship.js#L200`)

And only the scrolling never affects the performance. bad performance of quotes tab is caused by 3 times of big quotes json loading and GC is suffered. tbh it's need to be optimized. fortunately it's just used by devs.

**Comment by sinsinpub** [comment]
I think the better impl u r describing:
change the ship list rendering mechanism(`execute` part): don't clear elements of whole tab; build ship list once, just update necessary data (only quotes tab has data to be updated in fact); only re-rendering ship elements on the right part when another ship is clicked, keep the left list unchanged.
so the position of ship list will be remembered automatically, and better performance.

**Comment by Javran** [comment]
@sinsinpub ah I don't mean scrolling the list has poor performance, just that every time you click on one list item, `execute` gets executed -- so if there's anything initialized in `execute`, it has to be (unnecessarily) re-computed, this includes list item removal and re-insertion you've mentioned. anyway from your response I think you've got the idea.
