### ISSUE TITLE
Game won't load with VPN

### ISSUE THREAD

**Issue by Dord-san** [KC3Kai/KC3Kai#1390]
I know KC3Kai doesn't need a VPN in order to play. However at day time my internet download speed gets throttled and to bypass the throttling I have been using a VPN recently. KC3Kai worked fine for a few days until I restarted my computer and found out Kancolle won't load at all with the VPN active.

This is the console errors I receive. 
http://imgur.com/rsFa5pn

The VPN I am using is VyprVPN. KC3Kai is at version 30.2.1. I have cleared the cashe and reinstalled KC3Kai along with VyprVPN and Kancolle continues to be stuck on a white window.

**Comment by LostLogia4** [comment]
It appears that the problem seems to have something to do with the VPN. Check the network tab and see what happens.

**Comment by Dord-san** [comment]
Followed your instructions. This is the only error/failure that shows up and nothing appears after.

http://imgur.com/XXuNu2a

**Comment by LostLogia4** [comment]
Looks like network congestion to me. Only way to solve it afaik is to find another Net connection to play the game.

Clearing the cache is actually self-defeating your troubleshooting effort, since the game have to re-download your lost cache when your Internet connection could barely connect to the server in the first place.

Not to mention that if your bandwidth is throttled, it'll take forever to download those game assets again.

**Comment by Dord-san** [comment]
Found the issue. PPTP 126-bit protocol doesn't seem to work very well with Kancolle in general. I've upgraded my VPN plan so I have access to OpenVPN and L2TP (256-bit) which solves the problem.

Thanks for the help.

**Comment by LostLogia4** [comment]
Now that is news to me. I've never used VPN so I didn't know that using different protocols would make a major difference.

Anyway, glad to hear that it has been resolved. Will be closing this issue now.
