### ISSUE TITLE
[Feature Request] Push notification to mobile phones

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#1403]
Like logbook, add the ability to push notification to smartphone. Logbook-ex accomplish this by using third party software like Notify My Android

**Comment by LostLogia4** [comment]
@c933103 what kind of notification?

**Comment by dragonjet** [comment]
interesting indeed

**Comment by dragonjet** [comment]
looks good :+1: 

![screenshot_2016-06-11-08-36-15](https://cloud.githubusercontent.com/assets/557312/15981959/426d9f5e-2fb8-11e6-8b30-e228ea2c8077.png)

**Comment by LostLogia4** [comment]
I wonder if it's possible to put delayed notifications...?

**Comment by dragonjet** [comment]
yep, it's up to us when to send notifications from the desktop app

**Comment by LostLogia4** [comment]
@dragonjet I mean, is it possible to send a notification so that KC3Kai don't have to be live when the notification is dfisplayed?

**Comment by dragonjet** [comment]
oh that's not possible, unless we save it onto the server which runs a scheduled job to check for queued notifs every minute

**Comment by c933103** [comment]
@LostLogia4 e.g. expedition return, morale recover complete, akashi repair or docking complete

**Comment by dragonjet** [comment]
which probably brings us to putting timers into the background script instead of the panel. as long as chrome is open, it would still count, notify, etc. but the goal of afk-ing and being notified still wouldn't be satisfied. would kc android have notification feature?

**Comment by c933103** [comment]
​kc android don't have notification feature now.

Logbook-ex support 3 notification services: Prowl, NotifyMyAndroid,
ImKayac. I don't know is there any better service than the three. Prowl is
ios only and NMA is Android only. ImKayac have ios client but the android
support is limited to via third party tools that support XMPP protocol.

2016-06-20 8:56 GMT+08:00 dragonjet <notifications@github.com>:

**Comment by chronomeister** [comment]
Another implementation of this has been done for 艦これタイマー on firefox. [SC can be found here](https://bitbucket.org/amano_rox/kancolle-timer-for-firefox). Look at chrome/content/gcm.js for the syncing code. That pushes it to a pretty barebones app. Dunno if amano is still paying attention to the google groups to accept invites for the apk. Seems he wanted to limit it as he was unsure how quickly this would hit the limits on a free plan with Google's Appspot. [But here's some screenshots of the app just in case](http://imgur.com/a/OOFht).  One button is a manual set and the other is clear. Looks like Android Programming 102. This exists only as a Android option this way, though it seems feasible to make it iOS compatible but my mobile dev experiences are very limited.

**Comment by dragonjet** [comment]
hm, one thing is that we might not put much effort into this. I want to see how the KC android port will play into this first.

**Comment by c933103** [comment]
I doubt it would do anything much given the kc android is simply packaged via adobe air

**Comment by Agc0de6** [comment]
@c933103 kc android is perfectly working without Adobe AIR

**Comment by c933103** [comment]
@Agc0de6 do you know how the kc android work with that while retaining the file structure on desktop ?

**Comment by DynamicSTOP** [comment]
If user has chrome installed then it can be done without making additional apk. Will look like [so](http://imgur.com/a/O2BH5). But it still require a server since i believe nobody wants to add private keys into extension.

Sending was made using this [service](https://documentation.onesignal.com/), but i think it can be done directly by using [GCM](https://firebase.google.com/docs/cloud-messaging/). Not sure.

P.S. dev from OneSignal said that they will support FF mobile 48+ and https://github.com/OneSignal/

**Comment by DynamicSTOP** [comment]
I want this feature badly. I am tired of keep missing my baux exped resend, because chrome doesn't wanted to interrupt my full screen apps. (and i got feeling i will need a lot of baux during spring).

I do prefer using site instead of making app, because i wouldn't deal with app updates for android\ios. 

If nobody from @KC3Kai/developers against i'll go for push notifications using onesignal and third party server that i rent. This actually would be configurable in settings and i am planning to make site code opensource once it's done.

**Comment by DynamicSTOP** [comment]
[ios 5 years plan in 2015](https://trac.webkit.org/wiki/FiveYearPlanFall2015)
Bad news. [service workers](https://developer.mozilla.org/en-US/docs/Web/API/Push_API) are still [not implemented](http://caniuse.com/#feat=serviceworkers) for ios (iphone\ipad\ipod).
Good news.
`Service Workers
 Becoming a more frequent request. We should do it. `
They are planned at least.

**Comment by ethrundr** [comment]
again, my concern regarding this case always the same:

How the data between KC (and KC3) is being sent to the remote server, and how secure the datalink is? And what data is actually going to be sent and stored in the remote server?

Sorry, but I cannot quite get the flow from the previous discussion.
I understand the general idea, but still can't figure out how it'll be done in specifics.

**Comment by DynamicSTOP** [comment]
@ethrundr 
So i am seeing it like this.
![push workflow](https://cloud.githubusercontent.com/assets/9434504/24333925/3c4924cc-1261-11e7-933f-c5cab9774adb.png)
It can be broken on two parts. First time and regular.

By First time i mean orange part. Starting from bottom. 
1. User using chrome (or ff) on his mobile device will visit website through https (thanks to letsencrypt team). And yes, i am planning to host first version on aws ec2 instance in Singapore.
2. On this website i would ask user to register through one of the popular OAuth (google\fb\twitter\github\etc). The only thing i am after on this step is remove (at least try to remove) any misuse of my website that can be done. I would like to ask as less user info on this step as i could and OAuth on google\fb\etc allows. 
3. Once OAuth step is complete user will be asked to subscribe to PUSH notifications on this site and receive his uniq personal key. This key is different from OAuth key. On this step i would receive an id from user device that i will use to push notifications from webserver to device. Also on this step most paranoid persons can revoke OAuth access. I am not planning to use it for anything anyway.
4. Key from 3. would be putted inside KC3 through options page.

Now to black part of the graph.
1. (local) I don't need anything from KC itself. KC3 is already doing all the job by collecting network info. 
2. KC3 through secure channel (https\wss) will send info to webserver in format like 
`{time:1490554758, text:"fleet 2 has returned", key:"%user key%"}`
3. Server once in a while will check it's pool of messages and if it's sees that time has come it will trigger send based on key(s) that he obtained from user mobile device. Sended info will be like so
`{deveciId:123123123, message: "fleet 2 has returned"}`
Though this can be extended. As you can see in my screenshot from [above](http://i.imgur.com/GF8jL6W.png), we can add image and i think can even control LED light colour for some mobile phones.

That's all. If user will want to stop receiving messages he can do it in his browser options, through website or simply by removing key in KC3 options. Best case is through browser options on receiving device since it would completely block any PUSH notification from website. 

What i am planing to store on webserver is:
1. device Id - (may be multiple) because i need to know message destination, right?
2. user key - because i need to know from whose kc3 extension i got message and whom i should send it
3. oauth ids - (not keys, like facebook user id)most likely hashed. Simply to allow user retrieve his user key if it's lost. 

On any misuse i can revoke webserver private keys that it use to send PUSH messages.
Planned basic options will allow anyone to switch to there own endpoint and use it instead of mine.
I am not planning to send ads or things like that. But i am interested in getting experience in PUSH notifications. 
I am not planning to ask\demand money or payment for this service. I think aws t2.micro will be enough and it's annual cost is something like ~100$ which i can afford.
I am not aware of any other way to deliver message from kc3 extension to device without renting a server that will manage message sending and\or writing your own app for google play\etc.

**Comment by DynamicSTOP** [comment]
If you want i can check if i would be able to grant some access to webserver for you, so you would be able to examine it by yourself.
And since user key part this feature won't be enabled by default for everyone.

**Comment by c933103** [comment]
All three third party apps/platforms I mentioned above does not require own server, and they are also more feature rich with functions like quiet hours for both prowl and NMA. Downside is that Prowl is a paid app and NMA is also rate limited for free user, and no delayed notification although the model being proposed above does not involve delayed notification either. The inability to send delayed notification via these existing services can be circumvented by telling users keep kc3 open all the time.

**Comment by DynamicSTOP** [comment]
>quiet hours

You will still want to ask user when should be quite hours used and i believe in any case it's better be done inside KC3, so no unnecessary requests will be made. Also having them inside kc3 will eliminate need of doing it in multiple places in case of user having both phone and tablet.


>does not require own server

Still requires third party app to be installed on device in case of NMA and Prowl. Can't find a lot of info on ImKayac but since it making it sending it to iOS it should require app too. I prefer using existing browsers instead. That's the only part i don't like there and sadly that's the only currently existing way for iOS.


>delayed

https://documentation.onesignal.com/reference#section-delivery
It has delayed notifications but i still thinking should i use them like described above or not since notifications might be cancelled by `bucket\food\cancel expedition` and i would need to make cancel request
https://documentation.onesignal.com/reference#cancel-notification
Though if i just store them on webserver i can simply remove them there.

**Comment by c933103** [comment]
The ImKayac thing work with anything xmpp so as long as you have any app installed on your ios that support xmpp then you don't need additional app.

**Comment by DynamicSTOP** [comment]
Well, i guess there is no other existing easy way for iOS anyway and waiting 3 years for webkit... would be sad :rofl:

**Comment by DynamicSTOP** [comment]
In the end all of that is configurable and can be done in anyway which user prefer more.

**Comment by ethrundr** [comment]
@DynamicSTOP Ah I see.....
Regarding the settings to the phone push notification, how about if we provide the settings in the web as well?

While KC3 settings will give the user globalized setting for all devices they linked, we still provide a individual setting for each device in the web, that will override the settings sent from KC3 just for that device. This will give user more flexibility if in a certain case he want to be notified about, let's say, only expeditions on one phone and about everything on the other. Or, if they want to be notified in all phone during workhour and only on one phone outside workhour.

**Comment by DynamicSTOP** [comment]
I am ok with that too. Hell, this looks like a huge settings page :D
I am not sure how good is current kc3 settings in case of dynamic number of elements so may be i'll do it on separate page or as kc3 strategy room tab if current wouldn't work well.

**Comment by DynamicSTOP** [comment]
Guess i'll stick to wss in web push case because of the following:
- I can track if game window is active based on mouse movement or\and game network activity and send notifications only when it's not by toggling active flag through socket.
- I can immediately assume that game window is closed if socket was closed.

the more i think about it the bigger and harder this ticket looks D:

**Comment by ethrundr** [comment]
Just take it part by part, don't swallow it as a whole XD

For now, I think we can broke down the project into three main area:
- [ ] Basic Mobile Notification
- [ ] Setting Modification
- [ ] Socket Detection

Also I've made a new Project in the Project phase to track out this ticket, as it'll be growing bigger and bigger by time.

**Comment by mikenzb** [comment]
Feature has been added, will close issue now.
