### ISSUE TITLE
Translation: Terms Standarization

### ISSUE THREAD

**Issue by Syntax7error** [KC3Kai/KC3Kai#1505]
Doing this translation of the quests in French helped me to notice that the English translation is not necessarily always correct.

For example, I realized that in fact there is no "division" in the Navy. The Japanese word 師 団 (division) is not used in the names of quests. The correct term is "squadron" (戦 隊, squadron, is used 50 times in the Japanese quests titles).

I already made the changes in the French quests.json file (using "escadre" that has a slighlty different meaning than "escadron", this last term being mostly used in the Army while the first one is used in the Navy and Air force).
Maybe it could be a good thing to make changes in the other languages.
I am going to speak of this to KanColle Wikia also (but I am not sure they'll make the changes).

**Comment by nonsensed** [comment]
I'm not very familiar with naval terms, so I took a look.

In English, a naval division is a subdivision of a naval squadron. Most of the IJN references are for example Destroyer Division ##, which is how IJN groupings are commonly referred to. Looking around for examples:
https://en.wikipedia.org/wiki/First_Carrier_Division
https://en.wikipedia.org/wiki/6th_Fleet_(Imperial_Japanese_Navy)
https://en.wikipedia.org/wiki/5th_Fleet_(Imperial_Japanese_Navy)
As you can see, "squadron" is used, but "division" is also commonly used and they don't mean the same thing.

Thanks for this. I wasn't aware of the distinction myself. Now I know to be careful about whether to refer to something as a division or a squadron.

**Comment by Syntax7error** [comment]
@nonsensed It seems that you are right.

I notice that the Japanese article equivalent article for the First Carrier Division is 第一航空戦隊, that is translated by Google by "First Carrier Division".
Here, 第一 means "First", 航空 "Aviation" and "戦隊" is "Squadron", but the two last words together are translated by "Carrier division"...

Actualy, I didn't know that there are two words for "division" in Japanese (at least), it led me to make an error.

However, some quests on KanColle Wikia are translated differently but seem to have the same words:
- A40: 精鋭「第三**戦隊**」全艦集結せよ！= Gather All of the Elite 3rd Battleship Division
- A42: 主力戦艦部隊「第二**戦隊**」を編成せよ！= Organize the Main Battleship Force: "The 2nd Squadron"

So there is still a problem somewhere.

The English Wikipedia seem to have the same kind of thing: in the article [18th Cruiser Division](https://en.wikipedia.org/wiki/18th_Cruiser_Division_(Imperial_Japanese_Navy)), the name written is 第十八**戦隊** (18th Squadron)

It would be much better to have some advice by someone speaking fluently both Japanese and English to answer this question, relying on my shitty Japanese and on Google translation doesn't seem to do good things... :sweat:

**Comment by ethrundr** [comment]
@Syntax7error as you mentioned it right, "division" is a term used mainly for land armies, while most naval used "squadron".

However, these two words, based on popular used, can be used alternatively. The public, though, will be more familiarized with Division, rather than Squadron.

So yeah, in line with this, it might be a good opportunity to set some default terms, whether we will use the "public meaning" or the "literal meaning".

@KC3Kai/translators tagging all Translators so they might know about this discussion.

**Comment by nonsensed** [comment]
My preference (other than being lazy and using whatever the wikia has up) is to refer to IJN groupings as they are listed in non-kancolle WW2 formal references like wikis or history books in our respective languages.

As for the English quests.json, virtually all of the translations are directly from the English wikia as far as I've seen. Personally I would love to go down the quests list and adjust a number of wordings to fit a bit better, but I have my hands full with my current masochistic hobby of working on the quotes.json.

**Comment by Syntax7error** [comment]
@ethrundr: it is sure that the "public" may use some words in place of others, because they don't know, or because they don't care. But I believe that it is better to do things right and to use the right words (even for a game).

Another example of inaccurate translation is for 秋刀魚の缶詰, in the items.json file, that has been translated to "Canned Mackerel", while it is "Canned Saury" ("Sanma" in japanese, a fish from Eastern Pacific).
Some may think it is better to use "Mackerel" that is a word that most people know, but I believe it is better to use Saury, because it is something really from the Japanese culture.
If people don't know what is a saury (like me before) and search what it is, it is a good thing: it will teach them something and make them less stupid. If they don't want to search what it is and stay stupid, that is what they deserve anyway! :stuck_out_tongue:

![](http://thumbnail.image.rakuten.co.jp/@0_mall/auc-kanbi/cabinet/tjmy/4902150118306.jpg)
Canned saury!

**Comment by ethrundr** [comment]
@Syntax7error now you make me hungry....

Well, we need to set some terms as our default anyway.
Changing the title into something more appropriate, so we can discuss **ALL** terms need to be standardized here.

**Comment by ethrundr** [comment]
tagging @dragonjet as well

**Comment by Syntax7error** [comment]
In fact, every language is different and some can have only one word to describe several things, while some other have one word for each (eg. translations in French of the English word "squadron" can be "escadron" or "escadre" depending on the army type).
Also, different countries use different names for the army groups and ranks, sometimes they can be similar but it is not always the case. With also the problem that KanColle is sometimes adapting the reality to the game (like for the use of the US [Hull classification symbols](https://en.wikipedia.org/wiki/Hull_classification_symbol) applied to the IJN, or the fact that Maruyu is not a ship but a class, etc.)
All this makes the standardisation of translations quite difficult, even for people speaking Japanese fluently, that have a very good knowledge of their own language, of the IJN, of nautic and military terms, etc.

There are also problems with the size of the sentences we want to use: if they are too long, they wont fit the location where they are supposed to be (this is a big problem for French, because we use many articles in our sentences, and words are slightly longer, eg. "Sortie Win Rate" is "Taux de victoire en sortie" or "<100% Supply" is "<100% Ravitaillement", that doesn't fit...)

It is certainly preferable to do the best we can with our own language, using the means of translation available, ie. Google translation (even if there are many problems as soon as the words have a very specific meaning) and Wikipedia (here also, some articles are avaialble only in some languages).
The best is to stick as close as possible to Japanese, while keeping the translations understandable and the game playable.

Anyway, it is always good to speak of translations problems from Japanese to English, because most of us do not speak Japanese but English, and the translations are mainly made from English, even if the help of the original Japanese terms is sometimes possible.

**Comment by ethrundr** [comment]
It is indeed that every language is different.

However, I still see we need to standardize some stuffs, especially in its english translation, before then it'll be re-translated to other language. This is just to minimizing confusion that may be caused, just like what you mention in your first post.

**Comment by dragonjet** [comment]
agreed with the standardization,
* another point is to also make our "term constants" easier to understand, e.g. `SettingsAS` might meed many things, but saying `SettingsAirFighterPower` would help translators more
* Chrome actually has a built-in internationalization mechanism, which we don't use at the moment. However, on their JSON files, each terminology actually has a description first to explain what it is to help translators understand each one. [See their documentation here](https://developer.chrome.com/extensions/i18n)
  * [related thread where this is discusse](https://github.com/KC3Kai/KC3Kai/issues/375)

**Comment by dragonjet** [comment]
to add:
* sometimes, we also need adjustments to interface. it should be a given that words are longer in other languages, and our interface should also acknowledged that fact and somewhat give consideration such as auto-font size if difference is not much, or ellipsis if it's just too long.

**Comment by sinsinpub** [comment]
@dragonjet Forcing to follow the Chrome locale setting (and i18n mechanism) is not a good choice for us, as our browser even our OS usually has a different display language we do not expect...
maybe just using as a Default value is fine.

**Comment by dragonjet** [comment]
true, I searched and it seems there's no streamlined way to force to use a specific folder

**Comment by Syntax7error** [comment]
As I mentioned it a week ago, 航空戦隊 seems to mean "carrier division" while 戦隊" is "squadron" (駆逐隊 specifically means "destroyer squadron").
I modified the French version of quests.json to stick more closely to the Japanese quests names.
The term "division" seems to be used only for carriers, while "squadron" is used elsewhere, so the quests A23 (123), A36 (138), A39 (141), A56 (161), A59 (164), A60 (165), A62 (167), A64 (169), B15 (225), B25 (250), B26 (251), B50 (287), B53 (293), B56 (296) and B69 (815) need to use "carrier division" and the others "squadron" (it can be destroyer squadron, cruiser squadron, etc.).

**Comment by Syntax7error** [comment]
After @Xwilarg told me that my translations of the ranks where too long and were overlapping the HQ experience, I checked the original ranks in Japanese and noticed that they do not correspond to the English translation:
- 元帥 = Marshal (currently Marshal Admiral)
- 大将 = Captain general (currently Admiral)
- 中将 = Lieutenant General (currently Vice-Admiral)
- 少将 = Major General (currently Rear-Admiral)
- 大佐 = Colonel (currently Captain)
- 中佐 = Lieutenant Colonel (currently Commander)
- 新米中佐 = Novice Lieutenant Colonel (currently Novice Commander)
- 少佐 = Major (currently Lt. Commander)
- 中堅少佐 = Mid-major (currently Lieutenant)
- 新米少佐 = Novice Major (currently Novice Lieutenant)

I checked with Google translation and double-checked with Wikipedia where it was possible.

There are two problems here:
- the English translation (and probably other translations made from this) does not correspond to the Japanese ranks (with also the problem that in-game Japanese ranks do not always correspond to IJN ranks, but it is an issue for the game itself, nothing we can do about).
- the accurate translation may be sometimes too long to fit KC3Kai panel.

Also, the Japanese in-game ranks seem to be Army ranks (ie. not Navy). Here is [Wikipedia's table of military ranks](https://en.wikipedia.org/wiki/Template:Military_ranks) for information:

![ranks](https://cloud.githubusercontent.com/assets/21103170/18378712/80cddee8-76a9-11e6-9f83-7886ba7e8901.png)

I will try to make something with the French translation. Maybe something can be done with the English one and the ones based on it.
Anyway, this is not really important as it is secondary and does not really concern the gameplay.

**Comment by Syntax7error** [comment]
Concerning the ranks, there are some little mistakes/adaptations that do not correspond to the Japanese terms.
Here are the accurate translations I could get using Wikipedia ([Comparative officer ranks of World War II](https://en.wikipedia.org/wiki/Comparative_officer_ranks_of_World_War_II)), with KC3Kai current terms between brackets:

- 元帥 = Grand Admiral (Marshal Admiral)
- 大将 = Admiral (Admiral)
- 中将 = Vice-Admiral (Vice-Admiral)
- 少将 = Rear-Admiral (Rear-Admiral)
- 大佐 = Colonel (Captain)
- 中佐 = Commander (Commander)
- 新米中佐 = Novice Commander (Novice Commander)
- 少佐 = Lieutenant-Commander (Lt. Commander)
- 中堅少佐 = Mid-Lieutenant-Commander (Lieutenant)
- 新米少佐 = Novice Lieutenant-Commander (Novice Lieutenant)

Note that "Novice" and "Mid" are not used in military grades and are Kadokawa's invention for the game.

Also, there may be a problem with the lenght of strings that can overlap HQ experience if too long (that's maybe why "Lieutenant-Commander"  have been abbreviated to "Lt. Commander").

Concerning the French translation of these terms, I think it is better to use WWII French Navy ranks, as anyway, the English terms correspond to UK/US Navies.

**Comment by Agc0de6** [comment]
@dragonjet How long rank field for now is (in symbols)?

**Comment by dragonjet** [comment]
@Agc0de6 actually depends on the font / letter. e.g. iii = m in terms of pixel space

**Comment by Syntax7error** [comment]
@dragonjet: what font is actually used here (to make tests).
It seems that the field is full with the letters "Capitaine de fré"

![](https://embed.gyazo.com/dc01a73327bb4e4e9c9c73738f7946ae.png)

**Comment by sebsmith1** [comment]
Since I enjoy this app, know something about this topic, and don't want you to screw it up, I figured I could give some useful advice on Squadrons vs Divisions both in English and other languages (especially French).

So the first thing to note is that French appears to have a word corresponding to the english division in use for small units that compose naval squadrons, at least if [this site is to be believed](http://www.naval-history.net/xGW-FrenchNavy1914-1918.htm#4). You should be able to find a similar Order of Battle in french which will have the equivalent french term; however, you should note that it might not be division. As an example, I'm pretty sure some navies use a term similar to flotilla here, so this might be where your confusion is coming from.

Next, at least in american usage, naval divisions really were the components of naval squadrons. A good example of this is [DesRon21](http://destroyerhistory.org/fletcherclass/squadrons/), which was composed of DesDiv41 and DesDiv42. However, we can also see this in a broader overview, such as [this one](http://www.fleetorganization.com/1941pacificfleet.html).

Third, you mentioned that languages don't always have the same set of distinctions, and I think that might be coming into play here. As an example, my understanding is the IJN didn't have different words for Cruiser Divisions and Battleship Divisions. However, I don't think you will add a lot to you translations if you try to keep that lack of distinction, given that you'd need to either make up a new word which isn't what any other source uses or assign one sort of ship to the wrong type of division. When the language you're trying to translate into distinguishes between two different things, it seems more natural to not collapse them into one term just because the source language does, especially if decades of reference material don't.

My understanding is that a naval division generally refers to between 2 and 4 ships of the same type, while a squadron is composed of at least two divisions. This causes some problems since neither unit is going to commonly have six ships like Kancolle fleets do. I see two good methods to standardize on here. First, you could make groups of four or less ships of the same type divisions (or the equivalent word in the local language for the time period) and make larger formation or formations with multiple ship types squadrons. Alternatively – and I'll admit that this is harder – you could refer to a reference [like this one](http://ww2db.com/other.php?other_id=15) to see what the historical formation's english term is.

**Comment by Agc0de6** [comment]
@Syntax7error, about **戦隊**.
Maybe we could translate it as "Battle Squadron"? In Russian naval language, we have "боевая эскадра" for this, which fits for battleship and cruisers.

**Comment by nonsensed** [comment]
Ah, I haven't really kept this updated with how I handle things, but @sebsmith1 yes, that's what I'm doing more recently for the English translations-- including the part where I find references for historical fleet names. The English Kancolle wikia more or less tries to stick with the USN terms for things, which I have adopted as my standard for English title translations whether I like the terms or not... and there are a lot that I do not like.

This is how, for example, instead of `Construction Corps`, I have chosen to translate the term as `Construction Battalion`.

Now, on the other hand, when mistakes occur with this naming convention, I do want to know about them so they can be corrected. That said, more than half of the English subtitles remain untouched and are still waiting review for these types of naming conventions. At this point, quest translations should be fully reviewed, so if there's a mistake with those, it's probably my fault.

**Comment by nonsensed** [comment]
I think this discussion has run its course.

A long time ago I did check the ranking translations as noted above. Didn't really see any inconsistencies to edit. (it was originally a much different post, but syntaxerror corrected himself after looking things up)

Corrections that need to be made in translations will likely be placed in a new issue rather than bringing this one back up. I fully welcome any more suggestions for changes-- please, let me hear about them. These tend to be interesting discussions.

If I'm wrong on anything or there are still unresolved issues to discuss, we can get this reopened.
