### ISSUE TITLE
A little question about english subtitles.

### ISSUE THREAD

**Issue by Xwilarg** [KC3Kai/KC3Kai#1506]
Hi,
I'm currently trying to translate dialogs into french, but I have a little problem...
I compared the Wikia of the game ( http://kancolle.wikia.com/ ) and the files, and... the translations really are different sometimes.
Let me take 2 examples with Ryuujou:
In the files: Hey... you, keep them hands to yourself.
In the Wikia: Ummm. You, don't touch me so much.
Let me take another example :
In the files: Thanks! With this, I ain't gonna lose to Akagi and Kaga. Like I ever would, a-ha-ha-ha-ha...
In the Wikia: Thanks! With this I won't lose to Akagi and Kaga, although that's impossible, a-ha-ha-ha-ha...
So, well, I'm a little lost...
Which one is the more accurate ?
Thanks in advance :).

**Comment by nonsensed** [comment]
The translations are different because I'm editing the English translations heavily (but slowly). I want to tell you the kc3 ones are better and more accurate because I did them !!! but I do live in constant fear of breaking accuracy when retranslating them. I would caution you when using English translations that you are using a translation and not the source material. The Japanese quotes file is the most accurate!

Ryuujou has a certain Japanese dialect, which in English is usually converted to a generic American southern accent. I used this concept to a degree when making changes in kc3's Ryuujou.

**Comment by Xwilarg** [comment]
Thanks for your answer :).
Saddly, I can't use the japanese quotes file because I don't speak japanese :/.

**Comment by ysigne** [comment]
Didn't know where else to ask this, but since this is translation related, are there any plans to make it so that the translations are read from a flat file somewhere? This could make translations easier to implement, and also allow people to customize their own translations.

**Comment by dragonjet** [comment]
@ysigne you mean per user only? or you want to edit a language file to be included in kc3 releases?

**Comment by nonsensed** [comment]
There will inevitably be differences between the wiki, wikia and kc3's subtitles (at least ones I have edited). For those who do not like changes I have made to the subtitles for one reason or other-- I would encourage you to contact me and discuss it so we can sort things out. You may find I am more receptive to criticism than you might expect. I can be found the most easily via the kancolle reddit discord, kc3-kai channel.

In particular, if I have made an error, please tell me! I absolutely hate myself every time I find an error I have introduced, especially longstanding ones.

As there have been no developments in this issue in the last >6 months and there is no specific bug to fix, I'm closing this.
