### ISSUE TITLE
Any chance we get a local cache option for modding?

### ISSUE THREAD

**Issue by Metchy** [KC3Kai/KC3Kai#1516]

**Comment by dragonjet** [comment]
Same discussion with #847

I'm sorry, no chance in the foreseeable future that this can be implemented.

Technology limitation, as we only use web technologies applicable in the form of chrome extensions. While this can be done in NodeJS, such things can only be done through installing/bundling executable software such as proxies. (Other viewers may already have these bundled or through a plugin because the viewers themselves are the downloadable apps). We don't install those. We're not a desktop app. We're just one-click install from webstore for the browser, and that simple installation will remain.

While there is actually a ray of hope to implement this in a chrome extension, it is not something we want to do. The idea is to read network traffic through a different method than how KC3 does it now (right now we read from network history `devtools.network` - things that have already been sent in an out which is 100% safe). The alternative method for reading network traffic that has the ability to modify the network, is through `chrome.webRequest`, and we can redirect requests to local copies of CGs. This is explained here

**Comment by Metchy** [comment]
I see. Thanks for the clarification. Cheers
