### ISSUE TITLE
Black screen Error

### ISSUE THREAD

**Issue by susukocok** [KC3Kai/KC3Kai#1532]
Recently i got problem with KC3 Frame. when i use KC3 frame it's become black screen like this. but there still a sound like always you begin to start the game. i'm using api and the admiral frame didnt appear but the game still works. but there is no problem when i directly play to DDM with your frame work. the frame works just fine except for trans quest and subtittle line ship girls. 

-my google chrome vers :55.0.2853.0 dev-m
-my OS: Windows 10 64 bit
-KC3 Kai vers: 30.9.1
-my build is that i use are the oone in google chrome web store
![kc3](https://cloud.githubusercontent.com/assets/22118294/18432695/a3bc214c-790d-11e6-8498-04c6b6578d05.jpg)

**Comment by dragonjet** [comment]
This involves chrome version. You're in an experimental chrome channel, and we will not fix anything on those versions, until we see the bug in Stable Chrome.

As of previous discussions this started Chrome 54(?), but will still be fixed in newer versions as long as you go back to stable chrome, re-open the game, then going back to preferred Chrome channel, and starting the game there (as long as you're not logging in to the version which caused it)

See discussion at https://github.com/KC3Kai/KC3Kai/issues/1531
