### ISSUE TITLE
"Play via DMM on frame" > "Twitter login" result in blank screen.

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#1535]
See http://imgur.com/a/9H5Tr

**Comment by dragonjet** [comment]
for now it is advised to login on a separate tab, then just open DMM frame afterwards

**Comment by dragonjet** [comment]
to help implement this workflow of login first before opening game tab, the menu now requires DMM login first. clicking on the menu will go to DMM login page, and after that, will show the "play" buttons

![ss 2016-10-09 at 03 43 48](https://cloud.githubusercontent.com/assets/557312/19215215/9e120728-8dd2-11e6-8f60-2863bfb459ee.png)

**Comment by Javran** [comment]
@dragonjet I would suggest leaving an option (probably turn it on by default but can be disabled for more experienced player) or try some other approach, now that whenever I start chrome fresh, it's a bit annoying that I have to click on that before I can see "play" in menu.

instead of opening a new issue, I'll reopen this one because it has contained most context.

**Comment by dragonjet** [comment]
#1551 was merged, and as of #1544, feature is by default disabled. will close this for now.
