### ISSUE TITLE
[BUG] Kills counter crashed

### ISSUE THREAD

**Issue by Agc0de6** [KC3Kai/KC3Kai#1540]
Chrome version - 53.0.2785.143
OS and its version - Win 10 Pro
64bit
KC3 Kai version - 30.9.2
running webstore version

Just last danced 2-5 and got this. WTF?
![2016-10-06](https://cloud.githubusercontent.com/assets/14156630/19132737/73315ac4-8b6e-11e6-8724-689ed7e623d9.png)

**Comment by Ivazhi** [comment]
Got the same problem

Same browser and kc3kai version

![screenshot_1126](https://cloud.githubusercontent.com/assets/22647754/19133321/a33519b2-8b92-11e6-96f3-37a5fc87f5e9.png)
![screenshot_1127](https://cloud.githubusercontent.com/assets/22647754/19133322/a33b96ca-8b92-11e6-8200-b6a7f40f2884.png)
![screenshot_1128](https://cloud.githubusercontent.com/assets/22647754/19133323/a33c4aac-8b92-11e6-98bc-af7539de545b.png)

**Comment by dragonjet** [comment]
this has been fixed in version `30.9.3` / `30.9.4`:
* https://github.com/KC3Kai/KC3Kai/pull/1538
* https://github.com/KC3Kai/KC3Kai/pull/1541 (re-release)

however, both are not yet released at the time of writing. 30.9.3 which contains the fix was merged but failed webstore publishing because I forgot to up the version number on the file. I'm re-uploading it now as 30.9.4.

deplucate of issues
* https://github.com/KC3Kai/KC3Kai/issues/1537
* https://github.com/KC3Kai/KC3Kai/issues/1539
