### ISSUE TITLE
Admiral panel loading on DMM website, but not API Link mode

### ISSUE THREAD

**Issue by nickL4K** [KC3Kai/KC3Kai#1562]
The panel on loads on the DMM website but not when i try to load it with the API link
Screenshots: 
![2016-10-26 - 22 27 38 cropped capture](https://cloud.githubusercontent.com/assets/23085636/19744055/19e29abe-9bcc-11e6-89b5-56b1bf2bea21.png)
![2016-10-26 - 22 26 41 cropped capture](https://cloud.githubusercontent.com/assets/23085636/19744056/1bb9af76-9bcc-11e6-9e69-8c94813a8c65.png)

Chrome version: Google Chrome	55.0.2883.21 (Build officiel) beta (64 bits)
Révision	b9eabca6f064bcaa5aa645e4b3eaba90cf47a43c-refs/branch-heads/2883@{#201}
KC3 version 30.9.4

**Comment by dragonjet** [comment]
Chrome stable is currently on version 54. We don't usually fix bugs in the non-stable channel since those are usually problems with Chrome itself and are usually fixed before it gets to the public.

Closing the issue for now until we witness this released on stable Chrome.

Chrome version statuses: https://omahaproxy.appspot.com/
