### ISSUE TITLE
Subtitle-Cursor detection and interface response

### ISSUE THREAD

**Issue by Dusk23** [KC3Kai/KC3Kai#1578]
If possible, make subtitle wrapping to mouse position toggleable?

**Comment by nonsensed** [comment]
Ah, beat me to making an issue on this.

Looks like the mouseover subtitles commit had the unintended side effect of making the subtitles flop around on accident constantly when the user plays the game normally. It's not working out too great as is, but it's awesome that the code now exists for detecting mouseover on subtitles now.

A couple of not-very-well-thought-out ideas to remedy this:

- Instead of changing the subtitle position, give it a 50% opacity when moused over (configurable opacity level in options?)
- Make this be an event that triggers when right clicking (or double clicking?). Kc3 would remember the user preference and keep future subtitles in the preferred position until the user right clicks again.

**Comment by dragonjet** [comment]
thanks for pointing this out @Dusk23 and @nonsensed 

unfortunately, since the trade out for detecting mouseover on subtitles is that it also blocks user clicks from passing through to the game. e.g. if you're on the quest page, we can detect his mouseover, but if we just make it transparent, it will also block the user from pressing the quest page buttons

the second suggestions is possible. since we made it pointer-active, mouseovers and clicks detected, we can make it so that clicking the subtitle will make it a ghost for 5 seconds. clicks pass-through and 30% opacity. :+1:

**Comment by Dusk23** [comment]
That seems like an interesting way to do it. Just to be clear though, is it possible to make an option for subtitles to just stay as they were? I am one of the screen-capture-happy players that uses snipping tool / puush / gyazo quite often and the text moving around so the text shifting around so much does make things a _tad_ bit annoying.

**Comment by dragonjet** [comment]
on the prevailing suggestion though, you'll need to click on the subtitles manually for them to enter ghost mode. so if you're just taking a screenshot or playing normally. it will stay the same as before this update

**Comment by sinsinpub** [comment]
😅 that why I always patch subtitles displayed outside of game screen. there's another 'complex' idea: Make subtitles text layer like a desktop lyrics:
 * Make subtitles layer as a text box without border, 3 or more quotes can be shown in it at the same time, new one fades in, older ones scroll up and fade-out. Ship name should be added before each quote to identify the speaker.
 * Have a editable state on which, show a bordered text box, could be moved around, resized. ofz possible to be moved outside game screen, making full  use of the space.

**Comment by dragonjet** [comment]
> show a bordered text box, could be moved around, resized. ofz possible to be moved outside game screen, making full use of the space.

I like this idea

**Comment by nonsensed** [comment]
(this is me pretending I have an idea of what I'm talking about when I probably don't! you can ignore me!)

Hmm, in light of @sinsinpub 's comment, and the fact that the event is in 10-20 days, can I make a suggestion? I think it'd take the least effort _short-term_ to temporarily revert to the previous system for how subtitles are handled. More _long-term_, you can see how sinsin's idea plays out and either keep both systems as an option for the end-user (if the interfacing seems different/controversial to the masses) or completely convert to the new system if it's functionally capable of looking the same.

I was honestly surprised to find how much my mouse always ends up where the subtitles are. Having the click block to ghost the subtitles might be more of a problem than I expected now that I've played the game for a day and had time to think about it.

Btw I like the idea of having 3+ lines be able to show up, but on the other hand, I also like having the quotes be "anime subtitles" style instead of "chat log" style. I'm not sure what to expect!

**Comment by dragonjet** [comment]
it's probably best though to let the user decide, so we'll have a "Subtitle Display" setting where he can choose one of the following:

* Fixed on bottom of game screen
* Fixed right below the game screen
* Bottom of game screen, moves to top on hover
* Bottom of game screen, ghost mode on hover
* Free-form, can drag-drop subtitle box
* Turn off subtitles
