### ISSUE TITLE
Kinu Kai Ni Icon

### ISSUE THREAD

**Issue by mikenzb** [KC3Kai/KC3Kai#1589]
Just making an issue to remind you to add in Kinus kai ni icon for whenever the next patch of KC3 is released.

**Comment by Javran** [comment]
just want to bump this issue as Kinu K2 has been available for a while without icons.
we probably can wait for incoming new kanmusu & abyssals but I think users would like to see this in next version if make one isn't time consuming.

**Comment by dragonjet** [comment]
ah tbh this is my least favorite part of updates :sob: 
yea, we can probably release it with the new ship icons incoming, that one I cannot run away from

**Comment by Javran** [comment]
@dragonjet last time I tried https://github.com/KC3Kai/kc3-icons it was not usable for some reason I can't remember (maybe some source code was missing). probably others can help creating icons if you could make that one work?

Despite that, I can make icons by taking screenshot in ship library, actually icons for asashio k2 (#1419) was made in this way, if that is good enough, I could probably help next time when I have time. (I'm going to bed though, so won't help with kinu k2 for now) but I'm not sure how abyssal icons are made, since they seems to have a red background.
