### ISSUE TITLE
Abyssal escort flagship displayed as alive despite sunk

### ISSUE THREAD

**Issue by Isaac020** [KC3Kai/KC3Kai#1633]
![2016-11-26 10 02 39](https://cloud.githubusercontent.com/assets/24190489/20640803/1786ff92-b424-11e6-9335-b679ac84bf7b.png)
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- [ ] Your Chrome version - via chrome://version/
- [ ] Your OS and its version
- [ ] 32bit or 64bit?
- [ ] Your KC3 Kai version - via chrome://extensions/
- [ ] Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- [ ] Screenshots which accurately paint the issue(s) you are facing.
- [ ] A step by step method that you did to describe how you got to that issue.

**Comment by LostLogia4** [comment]
I think this is because of indexing error, so the enemy escort flagship HP value was defaulted to -1.
Due to the unadjusted index, the actual HP is shifted to the unit next to it.

Escort Flagship = EscortHP[0] - unused
Escort Ship 2 = EscortHP[1] - Escort Flagship
Escort Ship 3 = EscortHP[2] - Escort Ship 2
...and so on.

**Comment by sinsinpub** [comment]
already fixed at master

**Comment by dragonjet** [comment]
marking closed unless experienced again after 30.12.0
