### ISSUE TITLE
Suggestion: prevent API call error message from popping up repeatly

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1666]
some user complained about this error message keep popping up (the problem itself is just #1664).
we might consider showing this message only once but leaving some indicator to warn user to be  caution.

**Comment by LostLogia4** [comment]
How about adding a timer for it?

**Comment by Javran** [comment]
I think that could also do, just need to lower the frequency of that popping up.

**Comment by dragonjet** [comment]
ah I'm thinking of probably triggering the "taiha alert" (though not the on-screen one, just the panel where we have red inner borders glowing), and preventing succeeding showing of that dialog, would that work?

**Comment by sinsinpub** [comment]
beside that, I think we should give a button for error report, when which pushed, a detail text including all version info, triggering api call, exception trace stack, will be copied into clipboard, to help people paste such a useful detail on their bug report of github issue.

**Comment by dragonjet** [comment]
while testing this, I learned that `onbeforeunload` does not fire anymore, and the user will be forcefully have their game closed when we update on webstore - even with "Exit Confirmation" enabled on settings. I also did console.log outside of the conditionals and it really does not trigger. (unless there is an unread chrome update that removes `onbeforeunload`(?))

special mode will not have this problem though, and by its release, we can update all we want. since the URL is DMM not `chrome-extension://`, any update to KC3 will not auto-close the game
