### ISSUE TITLE
[Question/Request] Would symlinking the contents of the extension folder in Appdata to it's equivalent in linux be enough to "sync" between two OS's in the same computer?

### ISSUE THREAD

**Issue by jonythunder** [KC3Kai/KC3Kai#1692]
I dual boot between windows and linux, and would like my KC3Kai data to be available to both OS's. I tried copy-pasting the contents of the extension folder, but to no avail (didn't try restarting the computer though. Most likely I didn't copy some other folder that was required). Wouldn't just a symlink or a copy of the folders be enough? I know my way around bash, so if you could just point me what files I need to copy and if I need to change something I would very much appreciate it (I would also post here whatever scripts I end up doing for this).

**Comment by kyoushuu** [comment]
Inside Chrome's Default folder in $HOME/.config/google-chrome and %LOCALAPPDATA%\Google\Chrome\User Data:
Local Storage/chrome-extension_hkgmldnainaglpjngpajnnjfhpdjkohh_0.localstorage
Local Storage/chrome-extension_hkgmldnainaglpjngpajnnjfhpdjkohh_0.localstorage-journal
IndexedDB/chrome-extension_hkgmldnainaglpjngpajnnjfhpdjkohh_0.indexeddb.leveldb

I usually put them in tarballs for backups and to import my KC3 Kai data to/from Linux/Windows, but symlinking probably works too. Doesn't work on dev version since the keys are different whenever you add a folder as extension.

**Comment by dragonjet** [comment]
I also believe symlinking would work, although cross-OS wise might have different results. Let us know if you have tried and we'd appreciate more info for things we haven't covered yet in case others are trying to do the same. @kyoushuu is right that this won't work if you got the source and loaded it as unpacked extension.

**Comment by jonythunder** [comment]
I have symlinked those files with success, been playing KC using KC3Kai and
the symlinked files for the last 24h without problems. Since I don't know
the inner workings of KC3 I can't say that there won't be any issues in the
future though. @dragonjet, is there something I should be keeping an eye
out for?

**Comment by dragonjet** [comment]
@jonythunder as long as you keep your chrome version the same on both OS, it should be fine

**Comment by jonythunder** [comment]
Roger that. I'll open up an issue ticket if something else goes wrong.
Thanks a lot for your hard work :)

Regards and happy New Year
