### ISSUE TITLE
[Discussion] opinion regarding ECMAScript 6?

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1698]
in short, I'm proposing to make ES6 available into our project, but to justify the use of new features (if not obvious) developers should give detailed comments (about what the code in question is doing).

for @KC3Kai/developers, despite the fact that we already have write permissions, I recommend use PRs for non-critical bug fixes (critical fixes or patch of just few lines might still be okay), new features and massive refactorings so other developers would have a chance to take a look and demand more explanation if necessary.

I know we had some discussion on ES6 previously (#918) and the main concern was readability. 
But my point is ES6 brings some good stuff, like `x => x+1`, `let` bindings and `for (var of ary)`, if used correctly these new features can prevent namespace pollution, simplify the code (for example, always feel `$.each` is an overkill on arrays but I'm too lazy to control indices explicitly myself) and even improve readability (for example `function(x) {return x+1; }` vs. `x => x+1`; `$.each(ary, function(i,x) {...})` vs. `for (let x of ary)`)

any opinion on this?

**Comment by dragonjet** [comment]
### ES6
I agree now with using ES6 since I've been exposed to a few more projects at work via nodeJS. However, I am still not familiar with its use in client-side, I mean, are we going to need preprocessors i.e. babel? NodeJS runtime already handles it but tbh I haven't made a build job before for compiling ES6.

I know chrome can support many of these stuff, but due to the way chrome updates these days, I am sure some of our players turned off chrome updates, and some of them go way back chrome 30+, or some just turned it off this chrome 54 just to avoid the black screens. and I don't know which functions will they be missing. though using a preprocessor will avoid this problem.

In general, I won't chicken away if we do agree that we need ES6, I'm fine with it and will adjust for the good of both the app and myself too. I can't stay living in the old school XD

### Pull Requests
I agree with PRs-first, unless it's a quick hotfix we need out very soon, we should probably have others take a look. I am also guilty with pushing straight to `master`, just to find out that even though it works, the goal / end result is questionable XD

In addition to this, anyone on KC3 org can review PRs, not just developers, as long as it's a peer review, having second opinion on stuff helps, not just to question the goal or the update, but also to get suggestions, quick related additions that would benefit those we didn't think of before.

Which means, you do not need to wait for my green light for a merge. As long as some are happy with it as well (would be nice if more than one person reviewed it though). We all own this now, since the time we moved the repo to the github organization XD

**Comment by sinsinpub** [comment]
np about ES2015 for me (yep, we should call it ES2015 :joy:), just remember to enable nodeJs harmony for travis. Don't import compiler/transformer like babal I think, stopped at Chrome 54 not affect support of ES2015, Chrome 30- is too terrible which should be updated.

I don't think there is always enough reviewer for us, even just look at the diffs, as long as stuffs don't affect him at all :joy: Some short-comes for overstock PRs:
 * PRs from other's repo hard to test, only 'review' on paper could be done.
 * PRs long time forget to merged take down contributor's enthusiasm.
 * Without manager's green light to merge and close a PR if only just someone is happy, it seems no different with non-PR. Diffs and comments still could be made on normal commit...

So my opinion about PR is: PR-first is np, but all of us should actively review and make a 'approved signal' (not only limited to a comment or a reaction) on github as soon as we see the PR. To let others confirm PR really reviewed and could be merged or not. I have personally viewed the file changes of all PRs since I'm involved into KC3, but mostly also no reaction at all. Recently [github's 'reviewers' feature](https://help.github.com/articles/about-pull-request-reviews/) should be full used to send the 'approved signal'.

**Comment by Javran** [comment]
for now I guess most ppl are good with bringing ES6 features into our project (not many active developers for these days though), maybe we can start moving towards it. I think @dragonjet have some statistics about KC3 users, does that include chrome versions? if so we can take a look and see how many chrome 30- users are around. if it turns out not being a large proportion, a preprocessor might not be necessary.

about PRs, we might need a "read before contribution" wiki page or something alike to reflect what we have discussed here. so to summarize what @dragonjet @sinsinpub have said:

- PRs are encouraged
- anyone in KC3 org, not just developers, are encouraged to review PRs (we can benefit from github reviewer feature as the link @sinsinpub just gave)
- the point of review process is not just for spotting techical errors but also for keeping an eye on readability - bringing in ES6 features means more black-magic can happen so we need more eyes to make sure the code is maintainable by other developers.
- once we have obtained enough approvals (depending on how many active developers are there) on a PR, we can go ahead and merge it - no need for depending only on @dragonjet for pushing the green button

**Comment by ethrundr** [comment]
Regarding this issue, I can help on merging the PR whenever I'm around (and I'll try to be around more often).

Just to make stuff cleared: we do this on every PR from now on, or just to those which utilizing ES6?

**Comment by sinsinpub** [comment]
@ethrundr I think should be every PRs.

A memo here: For known reason, some people had to stop updating Chrome at m49 for Windows XP. Only 92% of ES2015 supported. As a special bottom line of ES2015 features we can use, without a compiler.

**Comment by ethrundr** [comment]
Okay then.
For now, I'll merge the PR to master if:
*At least one member of KC3 org has reviewed it, and none is still requesting for a change
*The PR is labelled as `merge-ready`

**Comment by Javran** [comment]
2 things to do for this issue:
- rules we have established should be put into #1707 
- meanwhile setting up es6 support for travis (not sure if there are any other required changes?)

also I just took a look about es2015 support status, I think we will be fine as most of the selling-point features have been properly supported.

**Comment by Javran** [comment]
can someone open a PR that enables es6 for KC3? I'm not sure what to do except few jshint options, especially I have no idea if there's any other action required for chrome extension building, but we need a starter on this to push forward.

**Comment by dragonjet** [comment]
i dont think anything other than jshint needs it. the travis configuration for nodejs version only applies to the build process, not running the app itself so that one has no problem

**Comment by dragonjet** [comment]
We could close this now since ES6 setting is now merged, and further updates about contributing guidelines will be continued on #1707

**Comment by Javran** [comment]
@dragonjet I intended to wait for #1707 before closing, but as long as have one issue opened to remind us of settings guilelines I'm good with it.

**Comment by dragonjet** [comment]
ah #1793 would have the related issue threads listed

**Comment by Javran** [comment]
@dragonjet I see, just wanted to explain why this issue was kept open. I'm totally fine with closing it this one, let's move further discussions there
