### ISSUE TITLE
DMM frame crop not working

### ISSUE THREAD

**Issue by MoralSouls** [KC3Kai/KC3Kai#1761]
KC3 Kai - 30.16.1

Having the issue where when launching via frame, the game will show up scroll bars and it will not be sized to the window

![ss 2017-01-26 at 05 48 21](https://cloud.githubusercontent.com/assets/25363396/22326981/f7d4ed5c-e3ef-11e6-8e7b-9c35276b2362.jpg)

![ss 2017-01-26 at 12 04 58](https://cloud.githubusercontent.com/assets/25363396/22327005/0b7a4c3a-e3f0-11e6-82b2-9c5a2cb23085.png)

**Comment by mikenzb** [comment]
30.16.1 should've fixed this issue, are you sure the version number on the KC3 dropdown menu says "You're on latest" version? 

There was a new system in place to fix the auto-updating chrome likes to do during mid-sortie, just make sure you [update manually](https://github.com/KC3Kai/KC3Kai/wiki/Updating) if you aren't on latest version.

**Comment by MoralSouls** [comment]
I've checked and yeah, it is on latest. For me this issue randomly appeared even before update 30.16.0 and have not gotten this issue fixed since then.
![](http://puu.sh/tAOnP/df9b5ae753.png)

**Comment by sinsinpub** [comment]
seems caused by your jquery library should be loaded by dmm site is not correctly loaded.
if u know how to watch ur Network tab, check if u can access the library url like this `http://www.dmm.com/js/library/jquery_1_8_3/jquery-1.8.3.min.js`, your internet connection or other network related stuff might prevent u access it normally. that's why it randomly occurs.

**Comment by MoralSouls** [comment]
Sorry but how do I do that?

**Comment by Javran** [comment]
@MoralSouls open up your developer tool (F12 or ctrl + shift + j), this time select "Network" tab instead of KC3Kai, and you'll see a text box has grey "filter" text in it, in that textbox, type in "jquery" and see if there is something like `http://www.dmm.com/js/library/jquery_1_8_3/jquery-1.8.3.min.js` in the bottom list, it should look like the following:

![2017-01-27_001947_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/22361323/884ba962-e426-11e6-8d59-0fb80be618ae.jpg)

**Comment by MoralSouls** [comment]
Alright, checked and here are the results

![](http://puu.sh/tC9lc/b37cd10d8a.png)

**Comment by dragonjet** [comment]
@MoralSouls does the bug still persists?

the jquery used by our content scripts does not use/detect jquery from native DMM page. content scripts are sandboxed and cannot access variables from other side, vice versa. so we import our own jquery coming from the extensions. I say this really is odd, and is only likely to happen before 30.16.1

**Comment by MoralSouls** [comment]
@dragonjet still happening
![](http://puu.sh/tQKBV/6153da5084.jpg)

**Comment by dragonjet** [comment]
@MoralSouls the new version 31.0.1 should have a new gameplay option. we recommend using it in moving forward. we recognize that DMM frame and API links are now being a bit faulty because of recent Chrome versions, the reason why we made the new gameplay mode.

thanks for reporting, and let us know if you encounter problems in the new one :)
