### ISSUE TITLE
What's the fate of API link and DMM frame modes?

### ISSUE THREAD

**Issue by Beregondz** [KC3Kai/KC3Kai#1831]
After release 31 those 2 modes went thru a lot of troubles, I still can't make panel work with API and frame mode stopped working for a few days (black game screen with audio) then worked again, today stopped working.
I still think those 2 modes have their usefulness, API is a way to bypass DMM site troubles and play while it's down, DMM frame lets me manage the window independently from dmm site, being able to shrink other DMM games window without KC being affected.
Also in DMM site mode I have that annoying KC white button bar (tutorial, how to play etc) below screen where I usually keep subtitles, now it stretches everything and generates annoying scrollbars every time a subtitle shows up.
I don't know if it's relevant but when frame mode doesn't work the page keeps loading stuff for over one minute, then everything dies, this is an example of what it tries to load https://i.gyazo.com/b5ce51e345b117ed5322a4c9143044f4.mp4

I'm using chrome latest version with autoupdate 56.0.2924.87 (64-bit)

**Comment by nonsensed** [comment]
The reason for the new mode is because of Google enforcing changes on Chrome that are causing a wide range of issues with both Frame and API Link. This has been coming for I believe almost half a year, and the situation is expected to worsen. In order to be able to continue as a helpful tool for Kancolle players, this change was necessary. It's not that the development team as a whole wants to discontinue those modes, but rather that Google is forcing it to happen.

Any issues with the Play on DMM Website mode will have to be ironed out. It was only just released, so it's fairly normal for there to be problems to iron out.

**Comment by sinsinpub** [comment]
the two old modes are still able to work properly as long as u r able to do some settings on chrome. still recommend to try new mode first if there is no hard needs to use old ones as u said.

to solve DMM frame mode black screen with sound issue: disable flash killing feature flag at `chrome://flags/#prefer-html-over-flash`, to refuse chrome's replacement flash with html5.

to solve API link mode white screen not loading issue: add a command line parameter to chrome startup shortcut mentioned [here](https://github.com/KC3Kai/KC3Kai/issues/1755#issuecomment-274709076), to disable chrome's (not new already and forced testing on its users secretly) OOPIFs security feature.

**Comment by dragonjet** [comment]
summary: DMM website is also cropped and has backgrounds, subtitles, translations and everything you loved from old modes (except for annoying taiha). you don't need to worry about DMM ads and menus. try it out, but make sure to enable "Apply customizations"

if you need any other help, you may re-open this, or for faster response, ping us over at discord
