### ISSUE TITLE
[Feature request] Hidden debuff sound notification

### ISSUE THREAD

**Issue by Amelek** [KC3Kai/KC3Kai#1845]
Hi,

Would it be possible to add some kind of modal notification that would pop up when the hidden debuff is triggered?

Currently, game does it by playing quest completion sound when returning to the home screen, but it is somewhat easy to miss.

**Comment by martirsadota** [comment]
Bumping this issue up.

Currently KC "knows" when to play the debuff chime by monitoring `kcsapi/api_port/port` for the `api_m_flag2` key. The debuff chime plays when the said key's value is **1**.

AFAIK, we just need to do the same monitoring to be able to show a notification when a debuff is triggered.

I play KC with the sounds muted because I play at work, so visual feedback like this would be greatly appreciated. :+1:
