### ISSUE TITLE
[Request/Suggestion] About dead end nodes

### ISSUE THREAD

**Issue by IMCF007** [KC3Kai/KC3Kai#1888]
So I was playing 5-5. There are 2 reasons I'm not reaching boss node N; 1. Re make my ship(s) taiha or 2. Go off route. These 2 cases however record the same way on Sortie History (only battle node A D E).

I can check the result of E node battle with replay but I was hoping if there is easier way to know?

**Comment by Vultren** [comment]
I'm not quite following, but the recorded results only keep track of battle nodes. Node L is a blue node so it's not recorded. Is that what you mean?

**Comment by IMCF007** [comment]
How do I put it... Yes. I kinda want to know whether I reach dead end node or retreat at node E.

This come up when I was tracking how unlucky I was. Then I forgot how many times I went off route.

**Comment by Nya-chan** [comment]
Hmmm... for most admirals it would be enough to somehow visually see that they got a taiha at a node, because it means auto-retreat for most - would that be sufficient (and for the devs - can we get it from the node data)?

It would have a side effect of some of them seeing "Ah, I really continued with taiha girl, I am an idiot instantly", too w

**Comment by Vultren** [comment]
Checking the api from  EO shows that api_req_map.api_color_no determines node type, so maybe? the sortie records only show the first 5 nodes in the basic view so you need to drill down (ex. Summer 2016 E4)

**Comment by Vultren** [comment]
Hey @IMCF007 is #2197 what you wanted

**Comment by IMCF007** [comment]
Ah yes, that look nice (to me at least).

**Comment by ethrundr** [comment]
Since it already met the suggestion asked, then I'll close this issue.
