### ISSUE TITLE
Hitting tab on levelling page messes up textboxes

### ISSUE THREAD

**Issue by Accelyte** [KC3Kai/KC3Kai#1891]
### Versions:
Chrome Version 56.0.2924.87 (64-bit)
Windows 10 64-bit
KC3 v.31.1.1 Webstore using recommended playing method

### Steps to reproduce:
Hit tab on the levelling page. Easy as that.

### Actual behaviour:
![chrome_2017-03-13_23-00-06](https://cloud.githubusercontent.com/assets/21363469/23878811/7bc0654a-0841-11e7-8925-debf8b220b04.png)

### Expected behaviour:
I dunno...you tell me. All I know is that something's broken.

**Comment by Nya-chan** [comment]
This happens since the tab "jumps" into the textboxes which are actually always there, just shifted below the text.

A solution might be to give every input tabindex of -1, so they are not selectable via tab at all, if that is reasonable (and if we want them to be selectable when they appear, we can always edit this value via jQuery).

I'll have a look at it.
