### ISSUE TITLE
My turn, I guess...?

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#1916]
It've been a while since my last time here as well, and since @Javran in #1905, @dragonjet in #1909 and lot others has done theirs, it might be my turn to say now.

I joined up the hype as early as when Shimakaze still become the icon, way before the huge ban wave occurs. That time, I'm just a simple user, reporting error as I see them. But when the error is getting too much, I stopped using it altogether.

Several months later, the project changed it's name and starting to getting bigger and bigger day by day. Then I'm trying another luck to reinstall the extension, and it is working properly and neatly. Fast forward few months, then I'm starting to report bugs and joining conversation here on GitHub, alongside with lot of older programmers. Together, we create KC3kai into as big as what we've seen now: we can safely claim that at least half of current active players are using ours - whether they using it alone or together with other extension is not the matter.

However, nothing lasts endlessly. Unfortunately, this is time for final farewell. My time is not as much as it used to be, as well as my power. I'm getting busier and busier, which means my time here will be much much lesser then it already was. It'll be very rude if I insist to keep all posts given to me despite I'm being so inactive.

This does not mean I will completely leave the project I've come to loved and cared a lot. I will, if allowed, still help now and then on every aspects I'm capable to, either here, on Facebook Fanpage, or my own local group. I will also trying to keep myself updated with KC3kai (or Kai2) improvements as it is published.

Okay, enough story and texts.
All I wish to say now is: Thank you to everyone that has given me time and chance to be part of the project, and I hope I can still be the part of the next "phase" of the project. Wish you all the best for the upcoming phase. It's lot of fun to work along with you guys here.

Cheers~

_(ps: I will still be around, at least until the rebranding done and KC3kai is ultimately "closed". I wish to see the closure by myself.)_

**Comment by dragonjet** [comment]
Thanks for all the hard work @ethrundr!

Even though that you might have been inactive at times here on GitHub, but I still see you in social media groups dealing with the support from players asking questions or asking for help, since I am in your local group, which I not sure I should be :sweat_smile: I also see you post news and other updates there even though here in GitHub is not shown, but your efforts are still for KC3.

I still added you to @KC3Kai/product though. I removed the _Managers_ team which you were in before, as well as _Testers_ team to merge it into a new _Product_ team that can approve pull requests, and mark labels for issues, etc so just in case you come by, you can still assist.
