### ISSUE TITLE
De-duplicate Image Output

### ISSUE THREAD

**Issue by Adrymne** [KC3Kai/KC3Kai#1942]
Showcase Export, Screenshots and Replay Image output should share the code for outputting an image.

**Comment by sinsinpub** [comment]
definitely what i also want 👍 
remind: Uploading to imgur should be an independent, reusable module. Don't forget that images (urls) uploaded should be managed (saving to db, viewing at SRoom, etc)

**Comment by Adrymne** [comment]
I'm not sure Imgur upload needs to be its own module? I was planning on having the default behaviour being what I described in #1936 (use user-selected method, then fallback if they fail), but `saveTab()`, `saveDownload()` and `saveImgur()` will also be exposed so they can be used directly if necessary.

Also, I was considering opening the imgur link as a new tab after the upload finishes. Thoughts?

**Comment by sinsinpub** [comment]
i personally never use this feature to upload to imgur, because these uploaded anonymous things will not be controllable by myself 😂
there are two points:
 * imgur image link may be forgotten if only open in new tab once and never saved manually
 * not able to remove from imgur, because the management id (they call it 'deletehash') is not saved, even not shown.

although there might be few privacy info in these images, embedded replay data include more sensltive info
similar discussion: https://github.com/ShareX/ShareX/issues/389

**Comment by Adrymne** [comment]
It'd be easy enough to exclude specified methods from the fallback. We may even want to expose that option to the end user.

Adding the ability to delete images is possibly a good idea, but probably deserves its own issue.
