### ISSUE TITLE
Incorrect Great Success Rate

### ISSUE THREAD

**Issue by fourinone41** [KC3Kai/KC3Kai#1951]
Dev panel reports incorrect Great Success rate if mixed sparkled and unsparkled ships are used on a non-drum expedition. Currently it shows (# sparkled ships) x 19%. It should be 0%. 
https://puu.sh/uz0rI/ad7982e14d.jpg
https://puu.sh/uz0vU/519ffe7e0f.jpg

From the [original issue](https://github.com/KC3Kai/KC3Kai/issues/1690#issuecomment-269133444):
> Every ship you sparkle gives you a ~19% chance of GS, ie. 5 sparkled ships gives you a ~95% chance of GS. You are still however, required to sparkle all the ships in the expedition fleet if the expedition does not support overdrumming.

**Comment by Adrymne** [comment]
The error in question is easy enough to patch, but I'd like to make sure there isn't anything else that needs changing before I get started. The current behaviour of the GS chance display, as I understand it, is:

**Regular Expedition**
- If expedition requirements not met, output `???`
- If sparkled ships < 4, output `???`
- If sparkled ships >= 4, output `sparkledShipCount * 19`
  - *Proposed change: If shipCount > sparkled ships, output `0`*
- If sparkled ships >= 4, colour output gold

**Drum Expedition**
- If expedition requirements not met, output `???`
- If sparkled ships < 4, output `???`
- If sparkled ships >= 4
  - If not overdrumming, output `sparkledShipCount * 19`
  - If overdrumming, output `99`
- If overdrumming, colour output gold

I have two concerns. First, `???` seems to be pulling double duty as 'we don't know how to calculate this' and 'can't GS'. Second, the conditions for displaying the gold text seem unintuitive. For example:

Expedition 2, 4 sparkled ships = `~76%` (gold)
Expedition 21, 5 sparkled ships, 3 drums = `~95%` (grey)

(Also, can I get this assigned?)

**Comment by c933103** [comment]
* As I explained on discord, the sparkled GS rate for non drum expedition is not 19n%.
* If the above logic is used then when sparkled ship is 6 it would display more than 100%?
*You can GS with 3 ships too. Not sure about 2 ships.
*Do we have any data on overdrummed but not sparkled GS rate?
*I don't think drum expedition with sparkled ship that are not overdrumed would have that much gs rate

**Comment by Adrymne** [comment]
Forgot to mention GS chance gets capped at 99%.

Incidentally, I assume the discord explanation you're referring to is the following?

> data sample:
>
> 4 sparkled ships:
> exp2 248/316GS 78.48%
> exp3 120/152GS 78.95%
> exp2 203/254GS 79.92% (equipped with drums)
> 
> 3 sparkled ships:
> exp3 145/208 69.71%
> data source: http://bbs.ngacn.cc/read.php?tid=8314468

**Comment by Javran** [comment]
@fourinone41 do you have any reference about the ~19n% statement and "all ships have to be sparkled" one, other than wikia? I was expecting these conclusions to be found somewhere else, and I've tried wikiwiki and kancollewiki with no luck.

**Comment by Tsubakura** [comment]
> do you have any reference about the ~19n% statement and "all ships have to be sparkled" one, other than wikia?

This has literally been tested. Even if you had doubts about wikia's claim, implementing it as if a fully sparkled fleet isnt required for GS in non-drum expeditions while you're not sure, is basically jumping the gun too soon.

I mean, when implementing it, at least only include things you're absolutely sure about, even if you dont believe me. I had at least 3 people already trying to say the part on wikia which I have personally edited was wrong, and there were even attempts of people trying to change the article to something thats blatantly wrong. It basically caused unnecessary confusion and trouble on my end.

**Comment by Javran** [comment]
yep I admit I misunderstood the actual requirement and overlooked https://github.com/KC3Kai/KC3Kai/issues/1690#issuecomment-269133444 - and I haven't realized that until this issue came out. I wasn't sure, but I believed it was as good as what I could get at the time when this was implemented.

but anyways, that's exactly why this issue exists.

to settle this problem once for all, we need evidence, for me I can't find a clue how these conclusions are drawn. and it's only on wikia, I haven't found it anywhere else yet (except maybe zh.moegirl.org, I did found this statement there, but it sounds to me more like a direct translation of wikia's statement, and there's no related reference on that page either). if there are tests, I want to see a link to those results. just like I did in https://github.com/KC3Kai/KC3Kai/issues/1690#issuecomment-271064664 , this could be statistical results, analysis, etc. but it has to be something for people to see, without having to read and search through all discord chat logs - that's no helping others reading just this issue.

it's not that I don't trust you or something, I do believe want you are saying is true because I'm working on some other expedition-related stuff and users are reporting the same problem. but when I try to look for evidences and do the math myself, I realize there is no much around.

**Comment by c933103** [comment]
* For the "all ships have to be sparkled" statement, I have seen 3+ people tested that with total of 30+ trials without a single GS.
* For tests against 19n%, see the data and link quoted by Adrymne above

**Comment by Javran** [comment]
@c933103 thanks! I think that should be good enough as an evidence for "all sparkled" claim, we are not doing serious researches after all. also if I get this right, you are saying ~19n% is not true because it's capped at 99% ?

**Comment by Tsubakura** [comment]
Of all the encounters, I could only consistently find the most recent one, which happened to be last tuesdays. This should be more than enough as proof really.
![image](https://cloud.githubusercontent.com/assets/20300876/24841897/26eca624-1d8f-11e7-8005-15cf3c30bdd1.png)
![image](https://cloud.githubusercontent.com/assets/20300876/24841949/e9c8060c-1d8f-11e7-8a1a-6b0d0daeae38.png)
![image](https://cloud.githubusercontent.com/assets/20300876/24841954/fd543b8c-1d8f-11e7-9c12-55591c44cd90.png)
![image](https://cloud.githubusercontent.com/assets/20300876/24841985/7502cdce-1d90-11e7-8882-0e211c0c8ab7.png)

**Comment by c933103** [comment]
@Javran 3*19% is about 57% which is quite far off from the tested figure of 69%, although the difference is not that noticable when the figure is only displayed for fleet with at least 4 ships.

**Comment by Javran** [comment]
@Tsubakura thanks for the report, I think that's good enough

@c933103 I see what you mean, yes now I recall that when I was implementing this, I did suspect that `n=3` case didn't fit, so instead I just treated `min(19%*n,99%)` as a good estimation to cover `n>=4` cases and not worry about `n <=3` cases. so it ended up being that way.

@Adrymne your proposed change lgtm, do you want to get assigned on this?

**Comment by Tsubakura** [comment]
Mhm, I can concur with that. The test results so far does point that 5 sparkled ships equals to 19%, but the chances does not seem to scale lineairly. While we can assume 5 = ~95%, the same cannot be said for lower amounts, so that has to be investigated. 

On a sidenote, I have done some tests myself on whether not being able to achieve 100% with 6 sparkled ships is true or not on non-drum expeditions. So far, out of the 76 fully sparkled 6 fleet runs of exp 5, all of them succeeded. Its a small sample, but my suspicion is that you can just hit 100% success rate with 6 sparkled ships on a non-drum expedition, just like how I never ever saw a 4 sparkled + overdrum on a drum expedition fail. 

My guess is that people mistakenly tested 6 sparkled ships on drum expeditions and mistakenly believed to be this case, just like how you shown us a sample of exp 40 failing with a fully sparkled fleet, we know it uses a different formula after all.

**Comment by Javran** [comment]
@Tsubakura I've actually never observed any normal success on non-overdruming expeditions with 6 sparkled ships. so personally I'd say it's 100% but perhaps it's either what you are suggesting that people are mistaken overdrum expeditions, or wikiwiki / wikia want to be more on the conservative side.

**Comment by ethrundr** [comment]
@Tsubakura Unfortunately, I must say that the expedition Great Success rate, while mathematically possible, is technically impossible to reach 100% with 6 sparkled fleet, since I've tested myself, and faced 2 normal success out of ~50 expedition with fully sparkled fleet.

I'm assuming that with 6 sparkled fleet, the rate is capped at 95-96% (just like with only 5 sparkled fleet), as long as the 6th ship is also sparkled. Otherwise, it's flat 0%. I'm testing this on expedition 13 for around a month worth of expeditions.

Regarding expedition with ship amount lower than 5 ships, I'm assuming that each ship is weighted roughly between 10%-20% each, given that the entire fleet is sparkled. Any non-sparkled ship that contained in the fleet will simply drop the chance greatly - if not flatted it out to 0%. However, more data and research are needed to clarify this claim.

**Comment by ethrundr** [comment]
Regarding the overdrummed Drum Expedition, I also suspect that even with fully sparkled fleet, the GS rate is capped at 95-96% just like the sparkled Regular Expedition.

Next, regarding Drum Expeditions, the number of drums are comes first when calculating the rate, then followed by the sparkled ships. Sparkling a ship on drum expedition is not necessarily needed to get a high GS rate, after all: only overdrumming already give high enough rate to trigger it almost 3 up to 4 times per 5 expedition, based on my own experience.

**Comment by Tsubakura** [comment]
> Unfortunately, I must say that the expedition Great Success rate, while mathematically possible, is technically impossible to reach 100% with 6 sparkled fleet, since I've tested myself, and faced 2 normal success out of ~50 expedition with fully sparkled fleet.

Are you really sure that this is the case? I am talking about non-drum expeditions, since non-drum expeditions and overdrum expeditions both follow a different formula. Overdrum expeditions are 21, 24, 37, 38 and 40, and if one of your sample happens to be these expeditions, it obviously does not oppose my point.

Can I see your sample size of ~50?

**Comment by fourinone41** [comment]
@ethrundr Those 2 normal successes from 6 sparkled ships, can you post a screenshot and confirm they're not from expeditions with overdrum conditions? As @Tsubakura said, all instances we've seen were from overdrum expeditions, which may be explained by Vita version's data-mined formula.

Reposting from the old issue:

> GS chance = `21 + 15*#sparkled + drumBonus + flagshipLevelBonus`.
`drumBonus` is 20 if sufficient overdrum, or -15 if insufficient.
`flagshipLevelBonus` is a value applied to only some expeditions, with no real pattern, and equal to `floor(sqrt(LVL) + LVL/10) - 5`. Don't really know which expeditions in browser version this applies to, if any, since Vita's expeditions are all different.

> This would be consistent with that ngacn test: `21 + 3*15 = 66`.
**It also explains <100% GS chance for overdrum expeditions: if all ships are sparkled but overdrum is not met, `21 + 6*15 - 15 = 96`.**
Overdrum expeditions with 4 sparkled ships never failing: `21 + 4*15 + 20 = 101`.

**Comment by Adrymne** [comment]
@Javran I do, though I may hold off a bit on creating a PR to see whether a consensus will be reached regarding the GS formula.

**Comment by Javran** [comment]
um, despite this issue has been close, for those that still wonders success rate for non-overdrum expeditions with 6 sparkled ships, there's actually a way to search through your own expedition history quickly:

- open up any strategy room page, bring up the console in it (hit ctrl+shift+i and choose "Console" tab)
- enter the following 2 commands in the console:

```javascript
KC3Database.con.expedition.where("mission").noneOf([21,24,37,38,40]).and( d => d.fleet.length === 6 && d.fleet.every(s => s.morale > 49) && [1].indexOf(d.data.api_clear_result) !== -1 ).count( console.log )
KC3Database.con.expedition.where("mission").noneOf([21,24,37,38,40]).and( d => d.fleet.length === 6 && d.fleet.every(s => s.morale > 49) && [1,2].indexOf(d.data.api_clear_result) !== -1 ).count( console.log )
```
allow few seconds and 2 numbers will be printed out:

![2017-04-14_120854_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/25049020/988bc2f2-210d-11e7-95e4-39479f2244bb.jpg)

the first number is the # of times that you send a fleet with 6 sparkled ships but end up getting normal success (for non-overdrum expeditions of course), and the second, the # of ending up getting either normal or great success. if your first number isn't `0`, then we have found our proof that it's possible for a fully sparkled 6-ship-fleet to get normal success instead of the great one.

there is however one thing I'm not sure about: is great success determined before or after morale deduction? I think that great success is determined before morale deduction but I'm not 100% sure. if this is not true, we might need to further examine these cases with moral deduction in mind.

for those that knows what the code above is doing, don't try to use `api_clear_result === 0` to detect failures, for some reason that I don't know, KC3 records failed expeditions with `api_clear_result === -1`.
