### ISSUE TITLE
Minor equipment showcase text lining problem

### ISSUE THREAD

**Issue by Shurichan** [KC3Kai/KC3Kai#1962]
In "full" and "standard" modes, the equipment name and quantity of equipment looks fine.
But, in "light" mode, the text lining looks troublesome.
Happens with both english and japanese equipment names.
![2017_04_08_13_23_55_wcnhnpjfbzahwaaaabjru5erkjggg_1250_1389_](https://cloud.githubusercontent.com/assets/13228415/24828563/747e89b6-1c68-11e7-9ae0-70359ae5fed4.png)

**Comment by DynamicSTOP** [comment]
i would say it's not a mode problem but a single line equip text.
![default](https://cloud.githubusercontent.com/assets/9434504/24829563/7234df78-1c74-11e7-8acd-9bbe23b124df.png)

**Comment by DynamicSTOP** [comment]
how about this?

![default](https://cloud.githubusercontent.com/assets/9434504/24829849/f9b9dffc-1c79-11e7-8583-ec12d1562aad.png)

**Comment by DynamicSTOP** [comment]
Ended up with this two variants [Jp](http://i.imgur.com/cmmkfgg.png) [Eng](http://i.imgur.com/Al3MNkB.png)

**Comment by sinsinpub** [comment]
@DynamicSTOP no such necessary... because Japanese fonts installed on your (other's) system might be different, it's not possible to fit with only a little width 😂 
eg, my output (font auto mapped by system ofc) will need more space:
![image](https://cloud.githubusercontent.com/assets/160240/24830955/8024c6cc-1cc2-11e7-888c-07e0cee55518.png)

**Comment by DynamicSTOP** [comment]
Noooooooo...... then i need to move everything inside (...) on new line.

**Comment by DynamicSTOP** [comment]
Fix merged into master. Closing this.
