### ISSUE TITLE
Some weird promblem i'm currently facing

### ISSUE THREAD

**Issue by Asagi200** [KC3Kai/KC3Kai#2011]
### Versions:
- Chrome version - 58.0.3029.81
- Windows 8.1
- 64bit
- KC3 Kai version - 31.5.2
- Webstore version
- Custom Mode
### Steps to reproduce:
Just start up my chrome and the box is already like that(pic 1) .Tried starting the game and the different modes was already on top of each other(pic 2).After running,the words/stats just spammed when I hover over the ship(pic 3)
### Screenshots (if applicable):
- Screenshots which accurately paint the issue(s) you are facing.
![kc1](https://cloud.githubusercontent.com/assets/28261096/25580864/b35bc85a-2eb6-11e7-8047-2e5eaa562b6a.PNG)
![kc2](https://cloud.githubusercontent.com/assets/28261096/25580869/b5b18180-2eb6-11e7-851e-f1c496720a1a.PNG)
![kc3](https://cloud.githubusercontent.com/assets/28261096/25580876/b8c7f17e-2eb6-11e7-96ae-dad488920dfd.PNG)

**Comment by mikenzb** [comment]
Reinstall KC3 because you're missing the bootstrap.css from a failed chrome extension update or something along those lines, this bug comes up from time to time and from what I can tell there is no way to fix it besides reinstalling the extension. 

Make sure to backup your KC3 data if it's important to you.

**Comment by Vultren** [comment]
@Asagi200 Is your problem fixed.

**Comment by Asagi200** [comment]
@vultren 
Yea I reinstalled the thing

**Comment by Vultren** [comment]
Looks like it worked. Closing.
