### ISSUE TITLE
Bug in the Air Supremacy Value

### ISSUE THREAD

**Issue by Kirayao** [KC3Kai/KC3Kai#2025]
- Your Chrome version - Chrome 58
- Your OS and its version Windows 10 64-bit
- Your KC3 Kai version - 31.6.0
- Which build you have tried running? webstore version 
- Which game play mode you are using? Default 
- Screenshots which accurately paint the issue(s) you are facing.

http://imgur.com/Xd7Pt1F

As the screenshot shown, the Air Supremacy value shown on the panel is wrong.

**Comment by sinsinpub** [comment]
it's not bug, and it's caused by unknown abyssal ship/aircraft slots. as a feature for researching & verifying unconfirmed air power, the message u see is expected. 
we are not able to always update and guarantee its accuracy 😂 
if u would like to help us, u can post us the enemy comps from sortie history, and stats of all abyssal carriers from ship library.

**Comment by Kirayao** [comment]
http://imgur.com/a/Ipb8a 

I hope this would help.

**Comment by sinsinpub** [comment]
yep, it helps some. also need the air power of your fleet (on the long distance air raid node without any lbas support is best). and the stats + equipment of unknown abyssal (in your case, should be the Nu-class CVL), click on her face (the anchor icon) to direct to ship library page, will see the stats & equipment.

although we have already gotten some data, probably will update them later.

**Comment by Kirayao** [comment]
http://i.imgur.com/wmlidKx.png 

Maybe I should just upload the replay since it got more data?

**Comment by Kirayao** [comment]
http://i.imgur.com/g0D2GKv.png 
Another Replay. 
These 2 CVL got super high air supremacy values..

**Comment by sinsinpub** [comment]
yep, got your data. thx for help.
