### ISSUE TITLE
Vote on fighter power of combined fleet view

### ISSUE THREAD

**Issue by sinsinpub** [KC3Kai/KC3Kai#2070]
Since event Fall 2016, kc game mechanism changed on player combined fleet vs abyssal combined fleet, that is: both fleets 1 & 2 of both sides participate in air battle phase, that means fighters in player escort fleet also contribute to fighter air power.
see [wikiwki](http://wikiwiki.jp/kancolle/?%CF%A2%B9%E7%B4%CF%C2%E2#note2)

Air power section of KC3 panel when combined fleet view selected is intended to only take 1st fleet into account, ignore 2nd fleet. It's NOT 'wrong', because for player combined fleet vs abyssal normal fleet, it's still correct.

My question: how about simply sum air power of 1st and 2nd fleet when combined fleet view is selected? Or any other suggestion?

**Comment by flixwito** [comment]
+1 for air power summing.

**Comment by LostLogia4** [comment]
Hmm, so in a 12 vs 12 battle, both fleet's air power is counted in?

**Comment by LostLogia4** [comment]
In this case I think you should consider a toggle, with 6 and 12 below the fighter icon as indicator.

**Comment by ethrundr** [comment]
Agree with @LostLogia4.
Instead of plainly summing, making a toogle/trigger is better, to avoid accidentaly Air Power got summed even in normal fleet battle.

As for the trigger, if possible, here's my suggestion:
*First trigger is our fleet: If the fleet is combined, then it's true.
*Second trigger will be abyssal fleet. If their fleet is combined, then it's true.
*When both are true, summing performed. But when either is false, normal calculation performed.
