### ISSUE TITLE
[Minor Bug]About Quotes translation

### ISSUE THREAD

**Issue by Zelroth** [KC3Kai/KC3Kai#2097]
Quotes problems:
- Noticed no rainy season quotes traduction for Saratoga, Aquila , Kasugamaru, Warspite, Gangut.
- Hourly quotes Traduction come 2-5 min before actual quotes or don't show at all.(for all ships)

**Comment by mikenzb** [comment]
We're aware of both problems, the first issue is because the guy that normally does the EN seasonal lines is away right now and when he is back he will add them in for the next release. The reason why some seasonal lines are there is because they were from last year.

As for the hourly lines not working correctly, that has been an ongoing issue that most likely won't be fixed anytime soon. See more info in #1243
