### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by tsubasa231** [KC3Kai/KC3Kai#2106]
:3 I use Newest Chorme
I use windown 7 32 bit
When i use Kc3 i got error.Anyone help me fix it?
http://imagizer.imageshack.us/a/img923/8968/Ktfx3k.jpg

**Comment by Vultren** [comment]
I am only seeing a deprecation warning and no errors. Is the game loading after you open the panel? I am not sure what you are having problems with.

**Comment by tsubasa231** [comment]
-_- I don't understand.It not translate quest.It does not work anything 
http://imageshack.com/a/img924/8715/IYK5KI.png
http://imageshack.com/a/img923/7514/susquz.png

**Comment by mikenzb** [comment]
I can see you're using API mode, when you start up KC3 there is a warning there that states that it won't work. 
`Play via API Link - In some Chrome versions (55+), API Link is not detected by panel, and gets stuck at 'Waiting for game actions...'`

To fix this issue you need to stop playing via API mode, to do this just go to the Play KC button in the dropdown menu and enable `Toggle Features` (whatever you want) then start up by hitting `F12` and going to the KanColle Tab

**Comment by tsubasa231** [comment]
thank for help it work :D

**Comment by ethrundr** [comment]
@mikenzb In light of this issue, and since features in API are no longer observed, how about adding statement like: "_Any error observed while using API mode will not be fixed and no support will given while in this mode_" or alike.

I adopted the idea from Windows notification when a version is indicated as deprecated and then the support for it has ended. At least, this will let the user who are reading the text that we are not going to solve nor help any issue related to API features, as it is now all has been moved to the Customization menu.
