### ISSUE TITLE
KC3 showing "kills" left in 1-6

### ISSUE THREAD

**Issue by Neryungrisky** [KC3Kai/KC3Kai#2115]
![capture](https://user-images.githubusercontent.com/29667781/27503682-88d01532-58b9-11e7-8994-8e0a7462d47c.PNG)
KC3 shows the number of "kills" left for 1-6.
Since 1-6 doesn't actually have a boss that is killed, "runs" or some other word might be more appropriate.

**Comment by ethrundr** [comment]
Yup, it should be "runs".

**Comment by nonsensed** [comment]
"Clears" might work a little better.

"Runs" is often used to mean number of fails + successful clears combined. Or at least it is in my area of the gaming community.

(my free time is still pretty dead, sorry for lateness)

**Comment by nonsensed** [comment]
I've changed the EN term from kills to clears and "last kill" to "last dance" in the TL repo.

Now, I honestly still prefer to have it be "kills" for maps that require sinking a boss, so if anyone wants to implement a new term for 1-6, please do. Not really important, though.

Likewise, if people don't like the wording I picked, just say so and we can get it changed.

**Comment by ethrundr** [comment]
IMO, I'm also in for differentiating between three map types:

- One that require sinking a boss, will have word "_kills_" and "_last kill_" for the bar.
- One that require only to reach specific node without sinking a boss (like 1-6), will have word "_clears_" and "_last dance_" for the bar.
- One that require to cripple the bar based on boss HP (like one in event), will have the HP value instead of the word, like what is it now.

This is to make sure to accommodate if in future a map similar to 1-6 techs are implemented again.
