### ISSUE TITLE
Suggestion: Better SR Akashi toggle

### ISSUE THREAD

**Issue by mikenzb** [KC3Kai/KC3Kai#2132]
Just a small suggestion, currently the `Toggle Improvable` in the Akashi SR page works well however I would like to request a toggle to show Improvable available items only. 

Something along the lines of showing unequipped equipment only and items (equipment) required for the Improvement to be unlocked as well. At the moment the Akashi page will highlight equipment in yellow if they are locked however I want a toggle to basically disable that function and show only items in inventory & unlocked as green.

**Comment by NoxArt** [comment]
'm sorry as people spent time working on this, but I don't understand this change - when looking what can possibly be improved, I think the most important filter is what a player can improve at all. If an item is currently equipped - that is a trivial obstacle, you just unequip it and that's it, it's immediately turned improvable.

After the change - when pressing the toggle, it hides all the items we can potentially improve, those that just simply need to be unequipped. When not pressing the toggle, we need to go through all the items and evaluate whether they have red/yellow/transparent background (because it just shows everything) and it makes it pretty tedious and hard to go through.

If someone's usecase is different from mine, could it be made to work both ways, like it was before too?
Thank you for consideration

**Comment by NoxArt** [comment]
Oh, thank you!
