### ISSUE TITLE
Suggestion: Sortie deletable / Toggle when to record sortie / Choose what to backup

### ISSUE THREAD

**Issue by HitomaruKonpaku** [KC3Kai/KC3Kai#2167]
Just as title, I want to delete all 1-1 sortie (not other)

I have like 900 1-1 page now and backup / restore is the big problem (usually take me 8 hours to restore all data)

Hope someone can add the new feature

Thanks

**Comment by sinsinpub** [comment]
FYI, quick backup method: https://github.com/KC3Kai/KC3Kai/issues/2164#issuecomment-322659010

**Comment by ethrundr** [comment]
@sinsinpub 
Honestly, I myself also facing this particular problem, as my sortie history are quite a lot, especially on map 1-1, 2-3, 4-3 and 5-4 (yep, you can guess what I am doing there).
While I (and maybe several others) am understand on how to manually backup the files, it is still a good call to give a configurable purge option for each map if possible.

Logically thinking: if we can sort each and every sortie entry by map, why can't we use the same method to delete the entry for mentioned map?

**Comment by sinsinpub** [comment]
i see, building an independent page to manage the IndexedDB database is the requirement.
at least, be able to
 * counting current record count / space usage by tables (features) to let user make decision
 * let user selecting conditions / time ranges to delete matched records by tables

some other men said they would like to delete sortie data record by record via ticking a box on list, that sounds too inefficient... 😂 nvm, if anyone would like to contribute.

the thing i wanna remind is: before we resolve the foreign key reference issue, deleting old records from `sortie` & `battle` table will break the restore feature of Data Backup (mess up map history), because the rearrangement of primary key IDs of `battle` makes foreign keys in `sortie` inconsistent.

**Comment by ethrundr** [comment]
Nah, deleting sortie per entry is somehow feel too inefficient for me. Purge-per-map is already enough.

Regarding the restore function, this is just my idea, how about if we restore the database as is and then update the primary index of each table using the MAX id from each table? I know this won't be easy, since I'm also struggling for this on my own program, but several examples out there proved this to be doable.
