### ISSUE TITLE
Stacking finished missions

### ISSUE THREAD

**Issue by Croustade** [KC3Kai/KC3Kai#2177]
### Versions:
Chrome: 60.0.3112.101
OS: Windows 10 pro 64bit
KC3: 31.9.3 [Webstore version build]
Game mode: normal with all Toggle Feature on

### Steps to reproduce:
1. Select 5 missions (daily for fast).
2. Switch to another computer with same DMM account. Open Kancolle and KC3.
3. Complete all missions and receive rewards.
4. Switch back to the first computer and receive 5 new missions.

### Actual behaviour:
The finished missions remain on the KC3 board.
At new day it will reset back to normal. But before that time, it's annoying.

### Expected behaviour:
The finished missions gone.

### Screenshots (if applicable):
http://imgur.com/CbnLSEL

### Error Report (if applicable):
None

**Comment by nonsensed** [comment]
There are colored squares next to the quest translation in the panel. Click on one and then go to the main screen where you can poke your secretary ship. It will disappear for you.

You can manually clear quests using this instead of waiting for the reset.

**Comment by mikenzb** [comment]
![capture](https://user-images.githubusercontent.com/5982780/29599755-fca3fd2a-8825-11e7-93b1-aa47c42adcbd.PNG)
Issue should be resolved with the following above method, will close this issue for now.

The main reason why this happens is because you clear quests with the KC3 panel closed, KC android or use another computer etc.

**Comment by ethrundr** [comment]
Actually you don't need to navigate to home.
Just go somewhere that forces a loading in game, and the quest will be updated.
