### ISSUE TITLE
Disabling "Ship seasonal icons" does not work

### ISSUE THREAD

**Issue by Iksapalif** [KC3Kai/KC3Kai#2232]
### Versions: 
-- Chromium 61.0.3163.79 (Developer Build) (32-bit)
-- Windows 10 64 Bit
-- KC3 kai 31.9.9 Development build (downloaded from github release page)
### Steps to reproduce:
-- Disabled "Ship seasonal icons" in options page
-- Restarted chromium
-- Seasonal icon still enabled despite it being disabled in options
### Actual behaviour:
-- Seasonal icons are not disabled
### Expected behaviour:
-- Seasonal icons are disabled
### Screenshots (if applicable):
-- https://imgur.com/a/OciUc
### Error Report (if applicable):
-- none

**Comment by mikenzb** [comment]
So you end up with a master.zip file when you download the zip?

To disable the seasonal ship icons you must go into the KC3 settings and under `Game Information` and find `Ship Seasonal Icons` to disable them.

**Comment by sinsinpub** [comment]
sorry it was not clarified... zip package is not dev ver, it's the same package of webstore ver. so no regular icons inside it.

**Comment by Iksapalif** [comment]
Sorry I accidentally pressed ctrl+enter and ended up posting it before finishing it. My issue should be clearer now(?)

**Comment by mikenzb** [comment]
Like what sinsin said, those releases you find at `KC3Kai/releases` page are travis built pages that end up on the webstore, they do not have the induced normal non-seasonal icons.

If you would like to have the option for no seasonal icons you could download the master zip file [here](https://github.com/dragonjet/KC3Kai/releases) which just downloads the current code from our master branch.

It would be best to clone our repo since it allows for easier updating, if you would like to clone the dev build you may find more information [here](https://github.com/KC3Kai/KC3Kai/wiki/Setup-development-build#option-tortoisegit)

However I know Github now has it's own [Github Desktop client](https://desktop.github.com/) so that might be an option instead of TortoiseGit.

**Comment by Iksapalif** [comment]
I see, thank you.
I'll try installing the actual development build as you instructed for now.

**Comment by Iksapalif** [comment]
I tried loading the src folder and this happened: 
![image](https://user-images.githubusercontent.com/16525971/30508464-dd4dc466-9ac1-11e7-9f60-bd4bf7ffa52c.png)

**Comment by Iksapalif** [comment]
I installed the development build and [disabling the seasonal icon works now](https://imgur.com/a/6dTib), thanks everyone.

I hope this feature will also made it to the webstore build in the future, although it might be difficult with the limitations and all.

Closing as issue is mostly solved.
