### ISSUE TITLE
Horizontal and Vertical Layouts

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#225]
@bamboo3250 I just wanna make sure, both layouts have the same scripts right, and only the html/css are different? I mean is it possible to just copy-paste horizontal.js to vertical.js in case something gets implemented? I was just worried about the syncing between the two, making sure both are updated when something gets fixed on either side.

**Comment by bamboo3250** [comment]
Basically, vertical.js has more stuffs than horizontal.js but 90% of them are pretty the same. So I would say it will be safe if you can make sure HTML and CSS elements are available for vertical layout. If no HTML or CSS is involved, it's 100% safe.

**Comment by dragonjet** [comment]
like for example, earlier on 4a9dabc93fd82762d7efd7d122d34dcd8b9935af, I added a color that if ship is being repaired, instead of red, the HP becomes blue, on `horizontal.js`. I'm just afraid I'll need to notify you every time in cases like this XD

**Comment by bamboo3250** [comment]
If you are not sure how to do then you can just do it in horizontal.js. I can help you add it to vertical layout :stuck_out_tongue: 
btw, that code also works for vertical.js :+1:

**Comment by dragonjet** [comment]
just in case, can I edit vertical.js as well in case I do make some fixes?

**Comment by bamboo3250** [comment]
Of course, i still can follow though :3

**Comment by Crazyteitoku** [comment]
It has been several versions since this issue was being mentioned. Since then we have witnessed the deprecation of the default theme into the legacy theme and then with the advent of natsuiro theme being the standard. There is probably no real need to have a look at this issue.

Closing this issue for now as if there are any issues concerning the layouts should be addressed appropriately as such. We can open this issue later on if need be.
