### ISSUE TITLE
Lack of spaces in between some expedition data

### ISSUE THREAD

**Issue by johnwahlig** [KC3Kai/KC3Kai#2259]
_KC3 ver.31.10.2, macOS High Sierra 10.13.1, Chrome 61_

There is a lack of spacing in between the `Flagship` and `Fleet` words/numbers in the Expedition panel.

<img width="190" alt="screen shot 2017-10-03 at 8 58 39 pm" src="https://user-images.githubusercontent.com/27918605/31155779-a2074024-a87e-11e7-86d6-46fc8b63b144.png">

**Comment by johnwahlig** [comment]
(the highlighted `E` in `Exped` is my bad)

**Comment by johnwahlig** [comment]
If somebody can point me in the direction of the source file(s), I can fix it...seems easy enough.

**Comment by sinsinpub** [comment]
seems not so easy... because it might be some different rendering for different fonts or environments
on my side, it looks like this
![image](https://user-images.githubusercontent.com/160240/31158611-7a320882-a8f5-11e7-8d74-4c93b769c32c.png)

i'll add several pixels margin to these elements to force some spaces... 😅
