### ISSUE TITLE
KC3Kai won't update

### ISSUE THREAD

**Issue by Lanzerince** [KC3Kai/KC3Kai#2370]
I've been stuck with 31.9.0 for a while now, and it won't update at all. I've tried force updating it in dev mode but nothing happened.

**Comment by mikenzb** [comment]
Is your KC3 Kai closed before you press the `Update Extensions Now` button? Have you tried restarting chrome after you press it?

**Comment by Lanzerince** [comment]
It was closed when I tried it. In fact, only the extension tab is opened, and yes, I tried restarting chrome, yet nothing changed.

**Comment by ethrundr** [comment]
Try to remove the extension completely, then reinstall it anew from webstore (remember to relaunch the chrome first after removal, to ensure clean removal). After reinstall, then once again relaunch your Chrome and confirm whether it is working or not.

Make sure you backed up all the data first though, since removing will delete all existing data from current installation. You then may restore the backed up data to the new installation. However, please keep note that there is still a chance of missing data and numerous other discrepancies even with this backup-restore method. Some features also might not work with your restored data.

I suspect there is something gone wrong in your extension during the last update (in your case, is the update to 31.9.0), which render the application to trigger errors during update, thus cancelling the update.
