### ISSUE TITLE
The game does not start with kс3

### ISSUE THREAD

**Issue by Ristarchik** [KC3Kai/KC3Kai#2385]
- Your Chrome version - https://puu.sh/yxFXg.png
- Your OS and its version - windows 10 х64
- Your KC3 Kai version - 31.11.6
- Which build you have tried running? - Build with google Chrome store
- Which game play mode you are using? - standard (does not work any)
- A step by step method that you did to describe how you got to that issue. - Launching the application kc3 is standard via f12. 
As a result, the situation on the screenshot.
https://puu.sh/yxGc9.png Further the game does not load. All blockers and antivirus are disabled.
At start without ks3 there is absolutely the same. The browser was cleared from cookies of a site and a cache.

**Comment by mikenzb** [comment]
It sounds like a network issue, starting without KC3 causes the same loading screen?

Maybe try clearing your browser cache.

**Comment by Ristarchik** [comment]
The reason is that I did it once so 20. I do not know what you can do anymore.

**Comment by DynamicSTOP** [comment]
@Ristarchik 
There is **network** tab inside devtools. Open it and check that game api requests aren't blocked. They should be with ip address instead of domain name (ip is different depending on which server are you playing).

If you have adblock installed try disabling it.

If white ship isn't moving at all, try to resize browser window a little bit (might be flash bug).

**Comment by Ristarchik** [comment]
The ship does not hang. turned off the adblocks, in the Internet line a bunch of red js scripts. What is the reason why I do not understand.
https://puu.sh/yBicR.png https://puu.sh/yBig9.png

**Comment by DynamicSTOP** [comment]
Those error messages aren't very helpful :(

add **kcsapi** into filter box. see if any of the critical requests are failed or blocked.
![default](https://user-images.githubusercontent.com/9434504/33727483-d7876fdc-db80-11e7-9182-b2a90222ada9.png)
If all is ok (Status column shows 200) set **swf** as filter. See if anything wrong with getting flash files.

From errors in your console:  
You have problems with dc.js though it should be ads thing and shouldn't prevent game from loading. Probably blocked by some extension.  
**locale.js** shouldn't be related to kc3 or kancolle itself. It could be caused by one of the installed chrome extensions.

At this point i would recommend you to create new chrome profile, try to launch game without any extensions. 
![default](https://user-images.githubusercontent.com/9434504/33728549-6f6fd170-db83-11e7-8d15-48336e7c074c.png)
If it's ok try with kc3.

Also if you have discord you can find me in [KC3 server](https://discord.gg/RtSadWM). I know Russian :P

**Comment by DynamicSTOP** [comment]
based on network log. game stopped downloading game resources after Core.swf. 
reason was in unchecked caching in flash settings [here](http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager03.html). both checkboxes at the bottom should be checked.
