### ISSUE TITLE
KC3 Crashing when doing data backup

### ISSUE THREAD

**Issue by JokerD03** [KC3Kai/KC3Kai#2602]
### Versions:
Chrome Version: Google Chrome	67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)
Windows Version: Windows 10 home 64 bit
KC3  Kai Version: 32.67
Build: Web store version
Gameplay Mode: Customize DMM Website

### Steps to reproduce:
Go to Strategy Room
Click on Data Backup
Click on Export data to a file(.kc3data)
Click on OK
Extension crashes after 30 seconds to 1 minute

### Actual behaviour:
Chrome Aw, Snap! page displays
Exporting data does not seem to go beyond (0/3) before crashing

### Expected behaviour:
Display file to save after export

### Screenshots (if applicable):

![s1](https://user-images.githubusercontent.com/41476375/43002432-5350bdf4-8c5b-11e8-9333-2c9aaabf1e1e.JPG)
![s2](https://user-images.githubusercontent.com/41476375/43002437-589043f2-8c5b-11e8-857f-2c29985d90be.JPG)
![s3](https://user-images.githubusercontent.com/41476375/43002439-5af59d5e-8c5b-11e8-83f5-7b95a5c69679.JPG)

### Error Report (if applicable):
Not sure how to get error logs, sorry

**Comment by mikenzb** [comment]
Known bug, this will happen if you have a big database, it's recommended you manually backup instead by following this [guide](https://github.com/KC3Kai/KC3Kai/issues/2164#issuecomment-322659010).

**Comment by todkapuz** [comment]
Glad to see it isn't just me. Watched Chrome climb to 2.3GB of memory and then spazz out and die as above. Kind of a shame, only 2 years of data. Granted have slightly more data in csv from the 2-3 years before that in KCV etc but not nearly to the same detail. :)  Was backing up my main computer before trying to import the backups from my other 2 computers so I could have a complete history since I switched to kc3kai, since I can still find no way to actually do that right.  But all that said, care more for the efforts to go into the changes we all know are coming in less than 12 hours (assuming dev isnt the usual dev we know him to be).
