### ISSUE TITLE
Downscaling or Upscaling the game pixelates screenshots

### ISSUE THREAD

**Issue by Geisterwand** [KC3Kai/KC3Kai#3005]
Microsoft Edge | 85.0.545.0 (Official build) dev (64-bit)
OS | Windows 10 OS Version 1903 (Build 18362.836) (64-bit)
KC3 version 34.6.3 (webstore)

Taking a screenshot on anything other than 100% scaling will pixelate the screenshot. The pixelation is worse the lower you go. 

[Imgur album of screenshots on different scalings](https://imgur.com/a/0WnkRVg)

This did not occur prior to KC3 34.6.1.

**Comment by sinsinpub** [comment]
i guess u might have a discussion with @Tedster59 
because he said 'blurred' resized screenshots should be 'an issue', so i added the property `imageSmoothingEnabled = false` to screenshot canvas.

what i can do now, just add a new setting option to let u guys opt-in, just like other software 😺 
![image](https://user-images.githubusercontent.com/160240/84972149-d955cb80-b150-11ea-88b0-d967a2af194f.png)
