### ISSUE TITLE
C42 "Quarterly DesDiv 19 Exercises" 「十九駆」演習！ not tracked properly using Mission Completion 50% indicator

### ISSUE THREAD

**Issue by MachiMachiMachiMachi** [KC3Kai/KC3Kai#3028]
on 34.8.1
### Steps to reproduce:
1. Accept C42, then complete one PvP exercise fulfilling the conditions of the mission.  KC3 updates the status to 1/3 completed (correctly).
2. Revisit the Mission menu, which now shows a 50% mark next to C42
3. KC3 updates the status of the quest to 2/3 completed
### Expected behaviour:
The mission tracker should stay at 1/3 if the quest has the 50% mark activated
### Screenshots (if applicable):
![chrome_2020-09-01_21-56-19](https://user-images.githubusercontent.com/52080734/91934227-a7f49280-ec9f-11ea-8984-2e770049a35e.png)

**Comment by sinsinpub** [comment]
updated.
btw, because legacy quests of progress 1/3 is no mark at all (2/3 marked as 50%, 80% non-exists). for example:
![image](https://user-images.githubusercontent.com/160240/91943345-04eb5980-ed2f-11ea-8d9f-dc0c683b6633.png)

so if any other quest found that 1/3 is 50%, please notice us too. (for example, i'm wondering how it goes for quarterly C38)
