### ISSUE TITLE
Expedition 45 ボーキサイト船団護衛 UI does not recognize all valid fleet compositions

### ISSUE THREAD

**Issue by MachiMachiMachiMachi** [KC3Kai/KC3Kai#3030]
### Versions:
34.8.1

### Actual behavior:
Expedition window will show fleets with CVL (that aren't "CVE") flagship as not fulfilling all the conditions of the expedition, even though they do

### Screenshots (if applicable):
![chrome_2020-09-03_10-39-26](https://user-images.githubusercontent.com/52080734/92199776-eb303c00-ee2c-11ea-8a05-10a542667049.png)
![chrome_2020-09-03_21-26-20](https://user-images.githubusercontent.com/52080734/92199783-ee2b2c80-ee2c-11ea-8ecd-04b3f7efc73f.png)

Also see wikiwiki: https://wikiwiki.jp/kancolle/%E9%81%A0%E5%BE%81#Expedition07

**Comment by sinsinpub** [comment]
exped 45 updated to CVL. (wait for next kc3 release)

but kc3 exped planner is not a fullset of expedition strategy intelligence. so just a confirmed subset of fleet composition that can lead to success is used, alternative and not fully verified compos not included intentionally.

a real fact is: kc3's exped-related module is written years ago in another language instead of vanilla javascript, which cause the high difficulty to be maintained. nobody is able to hack alternative conditions into such a compiled module for now.
if anyone is able to and would like rework on it, perhaps all possible alternative fleets can be considered.

btw, wikiwiki's wording is also problematic: `護衛空母または軽空母(旗艦固定)1隻` can mislead to: `CVE at any position` OR `1 CVL as flagship`. 1 is meaningless, flagship can be only 1. CVE is included by CVL, `または` is not good wording.
`旗艦固定の軽空母(護衛空母も可)` can eliminate different meanings.
