### ISSUE TITLE
what is the "Clear only Ledger records in history" doing?

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#3072]
Profile→"Clear only Ledger records in history"

no info was found in the wiki.

i want to clean up some junk data.

e.g.
Expedition History
Crafting
Construction
LSC

**Comment by sinsinpub** [comment]
![image](https://user-images.githubusercontent.com/160240/103476505-762c3d80-4df1-11eb-8a3b-16e193a5dd86.png)
`Ledger records` mostly serves for this page, have recorded details of every resources & materials consumption.

i think u can not just clean 'some' data records of those types, to keep the 'auto-increment' sequence identifies of database tables consistency, u have to clean all records in those tables to reset the ID value to 1. otherwise, your later data backup/restore operations will be bugged.

if u still wanna do so, i can give u some scripts to clear all records of those data tables.

**Comment by ztjal** [comment]
@sinsinpub 

thx, i need scripts, del them is the best choice.

Expedition History
Crafting
Construction
LSC

**Comment by sinsinpub** [comment]
so before u do this, strongly recommend u do full chrome profile backup manually in the first time.
[Read this](https://github.com/KC3Kai/KC3Kai/issues/2164#issuecomment-322659010) to backup your data files, so you can restore them in case of anything going wrong.

1. Assume u have closed Chrome, backed-up data files, and restarted Chrome again. Don't start game, open Strategy Room page.
2. Open Chrome devtools by pressing `F12` or `Ctrl+Shift+I`
3. Execute following line (copy&paste it, then press `Enter`) to delete all `Expedition History` data:
```js
KC3Database.con.expedition.clear().then(() => { alert("Done!"); });
```
4. Execute following line to delete all `Crafting History` data:
```js
KC3Database.con.develop.clear().then(() => { alert("Done!"); });
```
5. Execute following line to delete all `Construction History` data:
```js
KC3Database.con.build.clear().then(() => { alert("Done!"); });
```
6. Execute following line to delete all `LSC History` data:
```js
KC3Database.con.lsc.clear().then(() => { alert("Done!"); });
```

note: although these lines can be executed in parallel, but still suggest to wait for each `Done!` popup to ensure database operation is completed safely, then do the next line.

**Comment by ztjal** [comment]
thx, it's done.
