### ISSUE TITLE
Mute function

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#324]
The mute function is so that I can mute the game for other games (like Touken Ranbu), The in-game volume option is only accessible in the main menu, so it's not really readily accessible.

As for the alarm, I would like it to be a repeating alarm sound, because you know, this might be the last warning before one of your ship sank for real.

**Comment by dragonjet** [comment]
Unfortunately, Chrome does not allow muting per tab only through extension's control.

However, there is a workaround for this, that can be manually done by users:
http://www.omgchrome.com/how-to-enable-tab-mute-chrome-feature/

> Go to chrome://flags in a new tab
> Search for the ‘Enable tab audio muting UI control’ flag
> Hit the ‘Enable’ link
> Restart Chrome

When you see the sound icon on the tab, it is now clickable to be muted.

**Comment by nekoworkshop** [comment]
+1 for the audio alert. Another feature I miss from KancolleSniffer.

**Comment by ethrundr** [comment]
@dragonjet as for the mute button, how about if instead of directly muting it, we forcibly change the volume setting into 0% while the mute is activated? later, when it is de-activated, the volume level is returned to normal.

For the audio alert when a ship is Critically Damaged, I also in favor for it. Make it as annoying as possible, and as catchy as possible, so people will be notified and realize that they actually have at least one ship with possibility to sunk if they advanced. Moreover, I'd like that this feature will have no setting to disable it. Annoying it may be, but we do this for the users sake :smile:

**Comment by LostLogia4** [comment]
@ethrundr All good and well, except for one tiny problem, escort fleet flagship are unsinkable, so an exception might have to be make for that one.

**Comment by dragonjet** [comment]
Taiha alarm now implemented, changing title to make this solely for the Mute function - which is right now not possible :sob:

**Comment by dragonjet** [comment]
As of Chrome 45+ muting is possible in the `chrome.tabs` API. Will try this out

**Comment by Yukinyaa** [comment]
Nice
