### ISSUE TITLE
Quest F92

### ISSUE THREAD

**Issue by ALTESINN** [KC3Kai/KC3Kai#3243]
Versions: Brave: 1.42.97 | Chromium: 104.0.5112.102 | KC3改: 35.5.3

Actual behaviour: Quest F92 depicted as SF3 quest (spring 2017).

**Comment by sinsinpub** [comment]
which language are you using? as far as i know, `Thai` has this issue, since its translations have not been updated for 4 years.
this game always reuses IDs of outdated time-limit quests for new quests, `SF3`'s ID 657 is used by `F92` now.
so as long as nobody would like to keep updating `Thai` (or any one u r using) translations, unfortunately workaround for you is switching to up-to-date translations, like `en`/`jp`.

**Comment by ALTESINN** [comment]
I'm using russian translation which has the same troubles. Thank you for answer.

**Comment by Agc0de6** [comment]
[Changed and commited](https://github.com/KC3Kai/kc3-translations/commit/d3e6d9d008c132f1f52d279365bbbcf467463f79)
