### ISSUE TITLE
Try to customize ship icon, but plugin report error

### ISSUE THREAD

**Issue by math-yyj** [KC3Kai/KC3Kai#3333]
Chrome version      127.0.6533.100 
OS and its version     win11
32bit or 64bit?      64
Your KC3 Kai version   35.6.28

what I have tried:

I switch to this folder

AppData\Local\Google\Chrome\User Data\Default\Extensions\hkgmldnainaglpjngpajnnjfhpdjkohh\35.6.28_0\assets\img\ships

and tried to customize ship icon

for instance, I have tried to customize Mutsuki Kai 2's icon

434.png

![434](https://github.com/user-attachments/assets/b705896e-6c23-49e1-aca1-8aa3c792dba6)

434_d.png

![434_d](https://github.com/user-attachments/assets/5ebba378-89c7-4aff-b15c-c9b248e88b46)

But within 1 minute，a warning showed "this plugin may be damaged", as shown below

Is there any way to avoid this warning ? Many thanks ! 

![20240810174248](https://github.com/user-attachments/assets/4ab21f3c-713d-43ef-a285-d886cbc95337)

**Comment by sinsinpub** [comment]
it's expected behavior. there is integrality verifications for extensions installed from webstore, you are not allowed by chrome to modify any part of extension files.

to do such a modification, you have to install kc3 by loading unpacked extension under chrome's developer mode. of course, this kc3 instance will not share data with your webstore instance.
