### ISSUE TITLE
Question about updated translation rules and such.

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#365]
1. As translations are now English-based, is the content in KC3Kai/src/data/translations/jp/README.md still true, and is it still true for other language?

2. what's the maximum length for the first parameter in battle.json's detection section?

3. Is it possible to test translations before they're merged and published onto chrome store?

**Comment by dragonjet** [comment]
1. Yes, the note still applies. Here's the order of events:

The very first intended effect was, using the Japanese source from the game's master data, we get a ship or item's translations from our built-in files, and if they don't exist, use the source, which is already in Japanese in game data. So for JP, leaving `ships.json` and `items.json` as empty files works.

@Diablohu did an enhancement to use English by default if it doesn't exist in the localized files. This meant JP will also use English by default so the intention above did not work, as pointed out by @kololz to me on wikia chat.

His update was really useful and opened the gates to better translation workflow. Like for translators to only need to include translatable words in settings and developers, not needing ids and values for localized files.

However, by that time, we still have problems syncing between languages, like additional developer entry still needed all languages to be updated, even though you only need to edit its developer description. Also, new translators must adapt to the huge settings object, which might get confusing.  

Starting #355 I changed it back to "each language for itself, if you don't have it, we'll use the source". So the `README.md` udner JP again applies. The downside to this is that if a language do not have a translation for some words, it will either show a variable name like `MenuPlayAPIDesc` which is also an intended effect to point out to viewers that the translations are ongoing and they don't need to report each "*hey I selected Filipino and this word is still in English*"

2) Right now we're using short-hands for `airbattle` in all interfaces, such as "AS+" and not "*Air Supremacy*". So right now it doesn't matter how long the full name is, but is just good to have on hand for later use.

For `engagement`, it uses the long hand "Green T", and it has a considerably small space, but I cannot specify what's the max exactly since it will also depend on the font, where right now `jp` and `scn` uses a specialized `font-family` when used

3) Since you already have your fork, you can clone it to your desktop and load it onto you chrome via:

https://github.com/dragonjet/KC3Kai/wiki/Setup-development-build#step-2-install

**Comment by c933103** [comment]
1. so if I understand it correctly, ship/item name in traditional Chinese that share same name as they are in Japanese can still omit those entry, right?
2. What i were asking was the "detection" section.
3. i see.
4. the current terms.json do not ask translation to translate the word pixel, which i think it would be used in setting page?
5. And you have mentioned theme names are not there because name are not translated, but i believe names are usually getting translated in Chiense, Japanese, or Korean, even like for themes that have a name "V-Ten", it would be translated into something like ビー・テン in Japanese, 비텐 in Korean, or 威天 in Chinese according to its sound. Actually, I have just checked wikipedia and all 4 skins of it are translated in both Japanese and Korean, with 2 out of 4 skin name translated in Chinese language.

**Comment by dragonjet** [comment]
1) Yes if there are languages who also want to use the Japanese source, no need to have the entries. Just leave those two files as `{}`

4) Yes, for some technical terms, I think we do not need to translate them. I dont event recommend translating things like `background-position` on the settings description "*See CSS background-position property*" where I saw one language I was transferring, didn't have the `background-position` word. These are terms that we also use in code, if curious people were to search for it `background-position` keyword would still show the best results. About `px` being also used in code, would be not recommended to translate, in the mindset that the user is also being a dev himself inputting `20px` in code.

5) I think this one is subjective really. Depends on our software if we want it to. Though in my perspective I prefer all theme names to be of the same names. That if we ever implement specialized themes like [Echo](http://kancolle.wikia.com/wiki/User:EchoHolic)'s, it would include romanized "EchoHolic" in all languages in respect to the one who made it.

**Comment by c933103** [comment]
4. I believe the term used in setting panel is pixel/pixels not px.
5. Well, just that i think some people would not have enough English knowledge to understand what is the meaning of words like "dark" or "default".

**Comment by nicky008** [comment]
@c933103 
In the 4th point; I think your suggestion is also good for normal persons (everyone) who use this KC3改. Some people might have any no clues about what `px` mean is.

In the 5th point; How about "more guiding in the theme selection"? because these themes really have their formal names (aka. technical terms). And like in the @dragonjet 4th point, in the view of webdevs, the technical terms should be use in English for referencing BTW).

In the 6th point; For now this app has no font customizing mode yet. Might be good if we are implemented this for more flexibility (with no any problems with CSS-based coding).

**Comment by c933103** [comment]
@nicky008 
for the point number 4, what i mean was the text being used in the interface now,
and for the point number 6, I just heard DJ said on another issue that it's hard to say about character limit in exact, due to difference in font usage or etc., (or was i misreading that part).

**Comment by dragonjet** [comment]
4. hm this is a tough call. Then in moving forward, we will add those `pixels` and theme names onto `terms.json`, though it is the choice of the translator to edit or not. We just have to note that it's not recommended but all boils down to, if they think its understandable enough in local language or not. I understand things get awkward in some languages, so at least I'd like to give them option to do so.

6. We apply custom fonts throughout the whole web page if using specific fonts founds in `\src\library\modules\Translation.js` under `applyHTML` function. If another language needs a special font, they may add it or create an issue for us to add it.

**Comment by nicky008** [comment]
@c933103 Oh, I see... I tough you were suggesting on something other than the interface.

**Comment by c933103** [comment]
@dragonjet .. @kololz said (1) is not true for equipment now?

**Comment by dragonjet** [comment]
hm let me see, I will update the Localization article on the github wiki today

**Comment by c933103** [comment]
ok....?

**Comment by dragonjet** [comment]
up

**Comment by c933103** [comment]
still...is https://github.com/dragonjet/KC3Kai/commit/f7acc5b6705dd867d70b13c14b21d44e735e1fb4#diff-1d4d9b72605d0442271ca8623f986f2b needed?

**Comment by dragonjet** [comment]
right now, yes - even if the characters are the same with Japanese
the exception was made only for `jp` settings that will not extend romaji ships and items
unless you may want to add an exception for `tcn` as well?
are the characters the same?

**Comment by c933103** [comment]
50% equipment name and 80% ship name have same character in both tcn and jp. And to regular tcn user, untranslated name in jp are more understandable than en. Therefore I think it would be a good idea to add tcn into the exception. (scn's condition is similar too but the percentage of exactly same character would be lower than tcn)

**Comment by dragonjet** [comment]
now added to exceptions 712b0b9d3fd02cf37e8f0f3f805db8691237fbb1

**Comment by dragonjet** [comment]
because of age, will be closing this since it seems questions have been answered and the commit for the request has been made. if there are other translation concerns, we can create a new ticket.
