### ISSUE TITLE
Cannot Update KC3

### ISSUE THREAD

**Issue by daaurpoj** [KC3Kai/KC3Kai#385]
Hello, my issue right now is that my chrome extensions page says I'm at v10.8. I went on extensions, checked the dev mode box, hit Update Extensions Now, but nothing is happening, I've tried it with the game running and not running, and tried closing and reopening my browser a few times. Is there something I'm missing here?

**Comment by Crazyteitoku** [comment]
Which build are you running? webstore build or github build?

**Comment by daaurpoj** [comment]
I am using the webstore build.

**Comment by Crazyteitoku** [comment]
Check to see on the webstore page if there is a new version available and that the version is different from yours. See if you can try and update from there.

**Comment by daaurpoj** [comment]
No new options, just says the usual "Added to Chrome". However, one hour ago a support topic was posted that read "Download Error
Can't download the extension. A network error dialog box appears after pressing the "Add" button."

**Comment by Crazyteitoku** [comment]
You might want to try using proxies to get the extensions then. It appears the issue stems from networks from your end to Google server.

**Comment by daaurpoj** [comment]
Would reinstalling the extension be a bad idea, even if I saved the API link?

**Comment by Crazyteitoku** [comment]
No, it wouldn't necessarily be a bad idea considering that the API link would be erased as the extension gets uninstalled. Other than that any historical information you have will also be erased such as your resources, crafting history, LSC, etc.

The whole premise is to trace down where you are getting errors and I am willing to bet that it is most likely coming from your connectivity to the internet - certain routes are affected.

**Comment by daaurpoj** [comment]
How would you recommend I do this? Collecting Errors has given me no luck so far. I don't know if this is even close to related, but I've had some nasty recurring adware in my extensions lately that I've been working on tracking down, but I'm just laying out any info that may help here. I appreciate the time taken to help me out here so far, I'll be the first to admit I'm clueless to an extent here.

**Comment by dragonjet** [comment]
If it's alright with you uninstalling and re-installing would be a good idea. Though there is a risk that if you really have a problem with the WebStore, you might not even be able to re-install XD

**Comment by Crazyteitoku** [comment]
I think at this point in time it is best to first get rid of the adware/malware as that can potentially interfere with anything and everything. For getting rid of adware I suggest you try using something like hijackthis if you are somewhat formidable with how your computer normally operates (by means of startup programs and what not).

At this point in time for KC3 Kai, I suggest if it is possible to just try and download the dev. build of KC3 Kai from github. No need to uninstall the old KC3 Kai that is from the webstore just yet but disable it so that you can load the unpacked (dev. mode) extension and see if that works. If it works then it most likely would be your connectivity. You can try again considering that if it is an intermittent network issue - it might not be related to your computer alone and should in theory be solved.

**Comment by Crazyteitoku** [comment]
@dragonjet yeah I sort of wonder about that, if uninstalled it might not even be able to be reinstalled. So really at this point in time it is best to first dispose of the malware because who knows what the malware is actually capable of.

**Comment by daaurpoj** [comment]
The main problem with the adware is I uninstalled the program that it tagged along on, and did a couple full virus scans using stock casual anti-virus programs and come off clean, yet it still reappears every time I restart Chrome, as of about four days ago. (Let me be a cautionary tale to read all those pretty little check boxes before you click "Okay", not after. At least I'll never miss out on all those FunDeals) However, the tool you recommended seems like it is much more relevant for the problem I'm experiencing, so I'm going to attempt to use it. It was pretty stupid of me to not immediately make the connection that malware affecting my extensions might be the root of my problems involving my extensions.

**Comment by McDohl** [comment]
have you tried junk removal tool? it kills mostly all junkware

**Comment by Crazyteitoku** [comment]
Yeah adwares are very stubborn, they are often poorly coded when it comes to uninstalling the unwanted stuff - and those are most likely intentional. Running anti-virus may not fix it as it could be because of outdated virus definitions or it isn't designed to catch malwares.

It is really hard to say at this point whether or not if the malware is responsible for your troubles but getting rid of the major eyesore first would be ideal at any given rate. At least in terms of troubleshooting that is.

**Comment by daaurpoj** [comment]
Well, I've been looking into the issue, and I think I'm going to have to reinstall chrome, as part of many other fixes. And JRT did not remove the adware, sadly. Before I do so, what kind of issues could I look forward to if I tried to reinstall the KC3 extension after reinstalling chrome? I have my API link saved in notepad, but I'm not sure what other precautions I can do.

**Comment by Crazyteitoku** [comment]
A whole bunch of historical information that you have had with KC3 Kai is lost generally speaking, these are: resources, consumables, construction, crafting, LSC and sortie history.

As for the adware that still lingers I am unsure if reinstalling chrome would help with the issue as the adware could be hiding anywhere. If you reinstall chrome and you can still see adware then it is a definitive sign that it isn't coming from chrome and would therefore mean that you need to find ways to try and get rid of the adware.

**Comment by daaurpoj** [comment]
Sorry for being vague, it's not the only thing I'm doing to combat it, I've also been removing a lot of suspicious and shady startup programs and whatnot, but I've also discovered that a lot of my chrome settings have been messed around with, and I've been advised that reinstalling Chrome could be a good step just to be safe. However, I've been saving it for last just in case I don't have the need to. So all I'll lose is historical stuff? I would still be able to reinstall and play fine?

**Comment by Crazyteitoku** [comment]
Yes you would, the only thing really is losing historical stuff and API key. However, the API key really gets refreshed every so often so there isn't much point in keeping API key anyway.

If you could also afford is also try using CCleaner as you uninstall Chrome. Make sure that it tries to erase any files that may have stored in your User profile. I am not sure if reinstalling Chrome would necessarily make it run like new again if there are stray data floating somewhere within your hard drive.

**Comment by daaurpoj** [comment]
Sorry for not getting back to anyone for some time, personal circumstances got in the way. Well, I got rid of all the adware, but it appears I still cannot update KC3. I still have not uninstalled and/or reinstalled Chrome Browser or the KC3 extension, but I did reset my browser settings entirely. I'm still trying other solutions as well, but if anyone has any suggestions here I'd appreciate it and be glad to take a look.

**Comment by Crazyteitoku** [comment]
Are you on 64bit OS? if so you might want to have a look into getting Chromium and seeing if that might be a way to alleviate from having to reinstall Chrome.

Also another idea is to try another computer if you could to see if you are facing the same issue or otherwise try another OS if you are capable of doing that. By another OS I don't mean another OS from within virtualisation, it must be from a clean boot.

I still somewhat believe that your issue lies in networking. Either the DNS server is messed up or what. You could try using Google's public DNS servers and if that doesn't help solve the issue then it is somewhere within the network that is probably blocking you from downloading stuff from Google web store. Ideally you might want to ask around others whom happen to use the same internet provider as you are to see if they are facing more or less the same issue - cannot download stuff from Google chrome store easily. If not then it is probably your computer and/or your internal network is at fault and probably require a computer technician to diagnose your issue.

There are other workarounds you can try such as grabbing tagged webstore builds from github in ZIP format but ultimately it would be annoying having to do that constantly. In all honesty if I could pop around to your place and have a look at your setup to see if I can solve the issue I would but I can't and there's no way to know how you connect to internet. If all the aforementioned stuff fails I must reiterate that it would be ideal to seek out professional help physically because I can't see the issues you are facing and it is somewhat hard for me to visualise.

**Comment by Crazyteitoku** [comment]
Closing this issue because the issue has been stagnated. As of writing the issue lies specifically at user's side and not of the developer's side and with intermittent network faults (such as the inability to update or even download the extension) is not something @KC3Kai/developers can address to and more NOC specific.
