### ISSUE TITLE
[Suggestion] Improvement on Rank in Panel and Strategy Room

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#472]
In the Admiral Panel:
The rank should be clickable, to switch between: 
- Rank Title (Admiral, Marshal Admiral, etch)
- Rank Number (1000, 500, etc)
- Rank Points (as mentioned by @dragonjet in #122 )

In the Strategy Room:
The "Rank" row will be divided into three columns, each will consist the informations mentioned before: Rank Title, Rank Number and Rank Points.

**Comment by dragonjet** [comment]
I'm afraid the second one is not possible, and the user needs to go to the actual ranking page in-game to know his rank, which is not available all of the time. That said, it also will not update automatically if you go up or down the ranks and will need to revisit the in-game rank pages again. This means putting it on the panel will not be effective since the user will be seeing it in-game anyways. This is also ineffective for strategy room (which use more limited data, only based on what panel saves on `localStorage`) thus will become outdated 99% of the time.

The third one is possible though, when we do apply Flonnaru's suggestion in the strategy room.

**Comment by nicky008** [comment]
Addendum: Not only be clickable but also have a hover box shown more details about how to cycle (look) more data too.

**Comment by dragonjet** [comment]
hm true, people usually dont explore the panel enough with the mouse to even know which are clickables and which have hovers. I even think 50% do not know the elos icon is clickable to switch between formulas

**Comment by nicky008** [comment]
And they also have this problem in the the HQ exp enhancements earlier too. :hushed:

**Comment by ethrundr** [comment]
actually I know that the HQ exp is clickable just after read your reply, @nicky008  :laughing:

**Comment by dragonjet** [comment]
wait the HQ exp is clickable?

**Comment by bamboo3250** [comment]
@dragonjet  I think you merged #458 :laughing:

**Comment by ethrundr** [comment]
@dragonjet yep, clickable: EXP to next Lv, EXP gained this Lv, Total EXP
![screen shot 2015-08-04 at 20 08 03](https://cloud.githubusercontent.com/assets/13522800/9061760/d3e986f6-3af8-11e5-8fd9-5d58fa77f897.png)
![screen shot 2015-08-04 at 20 22 19](https://cloud.githubusercontent.com/assets/13522800/9061761/d42af172-3af8-11e5-9eb4-dbba8176d700.png)
![screen shot 2015-08-04 at 20 40 23](https://cloud.githubusercontent.com/assets/13522800/9061762/d4623f88-3af8-11e5-958a-cab9a0faf391.png)

**Comment by ReiFan49** [comment]
someone called me?
![image](https://cloud.githubusercontent.com/assets/9847780/9063004/cd77a694-3aef-11e5-8302-a3b76c40baa5.png)

(well, sorry for no explanation for it lol, i guess it makes run out of space instead? meanwhile, the remaining,current and total taken from terms.json for the option itself lol)

**Comment by ethrundr** [comment]
@ReiFan49 rather than "Remaining", which waste more space, the old-'n-short "Next" is already enough to tell people that those number is the required exp to gain a new level.

Also, for this case, I prefer labelled one like the first rather the second which triggered by mouse over.
