### ISSUE TITLE
Just let me play now could use clarification when require panel to play is enabled

### ISSUE THREAD

**Issue by NicolaosGreene** [KC3Kai/KC3Kai#538]
The button that reads "Please load KC3Kai panel first" under the heading "Just let me play now" seems inoperative where previously, the button there would let you play the game regardless of the status of the panel.

**Comment by ReiFan49** [comment]
umm, actually because the "panel enforcement" toggle in settings were set to `true` by default ("Wait Panel for Load" settings)
maybe @dragonjet could explain the reason for leaving this to set instead unset...

**Comment by NicolaosGreene** [comment]
Ah thank you. I did not see it nor was there a note about it in the changelog. Furthermore, it might be a good idea to put a note under that button about that setting if you wish to change that feature since there are a fair number of settings. Also the fact that the button remained clickable and the text still read the same was a source of confusion for me anyway. That would be my two cents on this matter.

**Comment by dragonjet** [comment]
wait, I got confused by the settings xD
let's discuss this some other time, I'm still on guard for new data

**Comment by Nya-chan** [comment]
Probably obsolete due to recent changes in the whole panel logic :)

**Comment by sinsinpub** [comment]
...what's the fun to digging old thread by just trolling 😓  definitely no related with 'recent time' thingy.

**Comment by Nya-chan** [comment]
@sinsinpub Not trolling (sorry if it seems so) - I am browsing the issues for those that I can finish or those that can be closed, because to be honest, there seems to be a decent chunk of stuff that can be cut down to work on others and make it visually more appealing. There is the danger of the issue count just shooting upwards and people being off-put by the number itself, so from my experience it's good to get it pruned from time to time.

Anyway, my point - regardless of when the panel logic changed ^^; - is that "Just let me play now" is now gone, so this issue can be closed? Or maybe I am missing something in the startup tab?

**Comment by sinsinpub** [comment]
I agree with close this, tho message is not gone, but the option only applied to API link / DMM frame mode :joy:
