### ISSUE TITLE
[Feature request] kancolle-db.net integration

### ISSUE THREAD

**Issue by chronomeister** [KC3Kai/KC3Kai#690]
So I'm noticing more people being interested in kcdb. The people there wrote their own app for KCV and others to proxy chain through and deliver the info to kcdb. The main part of their module can be found here: https://github.com/about518/kanColleDbPost/blob/master/KanColleDbPost/Form1.cs

But the code in particular is this:
```
// oSession is, as you can guess, the original request/response from the kc servers.
string token = textBox2.Text; // token given by kcdb
string agent = ""; //currently unused
string url = oSession.fullUrl;
string requestBody = HttpUtility.HtmlDecode(oSession.GetRequestBodyAsString());
requestBody = Regex.Replace(requestBody, @"&api(_|%5F)token=[0-9a-f]+|api(_|%5F)token=[0-9a-f]+&?", "");
string responseBody = oSession.GetResponseBodyAsString();
responseBody.Replace("svdata=", "");

try
{
   WebRequest req = WebRequest.Create("http://api.kancolle-db.net/2/");
   req.Method = "POST";
   req.ContentType = "application/x-www-form-urlencoded";

   System.Text.Encoding enc = System.Text.Encoding.GetEncoding("utf-8");
   string postdata =
        "token=" + HttpUtility.UrlEncode(token) + "&"
      + "agent=" + HttpUtility.UrlEncode(agent) + "&"
      + "url=" + HttpUtility.UrlEncode(url) + "&"
      + "requestbody=" + HttpUtility.UrlEncode(requestBody) + "&"
      + "responsebody=" + HttpUtility.UrlEncode(responseBody);
   // next part is just how you do web requests in C#
   byte[] postDataBytes = System.Text.Encoding.ASCII.GetBytes(postdata);
   req.ContentLength = postDataBytes.Length;

   Stream reqStream = req.GetRequestStream();
   reqStream.Write(postDataBytes, 0, postDataBytes.Length);
   reqStream.Close();
}
```

Should be pretty easy to follow. token is kcdb's token provided when you sign in through twitter. Gets rid of any personally ident api info. Gets rid of the svdata header. Then sends the whole json to them for them to process. Otherwise just change from C# to javascript.

Doesn't require much in the way of presentation; On setting page just make a label (with a link to either website or explanation), a checkbox to confirm/deny sending data and then a textbox to put your token/key. Everything else is backend.

**Comment by nicky008** [comment]
I'm also a fan in KCDB too. :raising_hand: 

The interesting thing is the owner released the (module) code not so long ago for easy implementing.

**Comment by dragonjet** [comment]
Ah does this mean we also have to integrate Twitter signin per user?

Or is that token an app token to be used globally?

Overall, I wanna do this to :+1: 
Also, iirc there's also an online db @c933103 suggested to integrate, I forgot which

**Comment by nicky008** [comment]
There are 2 options available, that app's token (for Windows) and Twitter.

**Comment by dragonjet** [comment]
sounds fair enough
```
http://api.kancolle-db.net/2/
POST
application/x-www-form-urlencoded

Request params:
token // token given by kcdb
agent // user-agent?
url // api request url
requestbody // request data as text with api_tokens removed
responsebody // text response body with svdata= removed
```

**Comment by c933103** [comment]
for agent, see https://github.com/about518/kanColleDbPost/issues/3

**Comment by c933103** [comment]
and i just double checked that other online databased i have previously mebtioned do not support third party software submission

**Comment by chronomeister** [comment]
Ya, I would definitely seek the blessing of kcdb's owner before implementing this. I've been having troubles submitting data today so if the servers are already close to being overworked then adding how ever many would use it here would be of concern. That might also cover some of the holes there are right now.

**Comment by dragonjet** [comment]
hm alright, though is this the place where we can contact the owners?
https://github.com/about518/kanColleDbPost

or is there a more reliable way to contact them?

**Comment by chronomeister** [comment]
Here's his twitter for something different: https://twitter.com/about518 Should be a decent start.

**Comment by dragonjet** [comment]
thanks :+1:

**Comment by tasetase** [comment]
I tried to make a kancolle-db plugin for KCV, but the server replies Bad Request. I run the KanColleDbPost stand-alone submission application and it also spews Bad Request.

Did you also encounter this issue ?

**Comment by dragonjet** [comment]
not yet, the feature is still on queue atm

iirc kcv already has plugin for this, or is this the one I've heard, meaning yours is the only kc-db kcv plugin so far? I dunno where exactly I heard it though

**Comment by dragonjet** [comment]
Created request for KC3改 token: about518/kanColleDbPost/issues/8

**Comment by nicky008** [comment]
OP Handshake Repos :bowtie:

**Comment by tasetase** [comment]
The KCV plugin you probably heard of isn't actually a plugin, it's a custom version of KCV available on kancolle-db.net, so you can't just download the .dll and drop it in the plugins. Which means you either have to choose between kancolle-db KCV (which is just the original version by Grabacr07 + kancolle-db reporting) or yuubari/yuvuvn/whoever. 

I made an actual functional plugin .dll for KCV here https://github.com/tasetase/KanColleViewer/tree/kancolle-db-plugin/Plugins/KanColleDbPlugin but the only issue is the Bad Request stuff.

**Comment by nicky008** [comment]
Right, it's not really the official version. The current "allowed" custom version has no any problems for now yet because no any blockages from the owner. :3

The Bad Request problem might be on the server side (the owner's decision to allow our customized token).

**Comment by dragonjet** [comment]
@tasetase can I try doing a custom request using your `agent` key? and for the `token` I will use the one given to me on my twitter sign-in

**Comment by tasetase** [comment]
@dragonjet Go ahead, the agent key I'm using is the same one used in KancolleDbPost. Tell me how it goes.

**Comment by dragonjet** [comment]
seems I also got 400 bad request

![ss 2015-08-25 at 11 10 01](https://cloud.githubusercontent.com/assets/557312/9457850/e0360e6c-4b19-11e5-84da-a33cc0587d9b.png)

----
Also did this with `application/x-www-form-urlencoded` checked but same result


#### Data Sent
**Token**
The one given on my twitter sign-in

**Agent**
`LZXNXVGPejgSnEXLH2ur`

**URL** (url-encoded)
http://125.6.189.247/kcsapi/api_req_mission/result

**Request Body** (url-encoded)
```
POST /kcsapi/api_req_mission/result
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
Connection: keep-alive
Content-Length: 84
Content-Type: application/x-www-form-urlencoded
Host: 125.6.189.247
Origin: http://125.6.189.247
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36
X-Requested-With: ShockwaveFlash/18.0.0.232

api_verno=1&api_deck_id=4
```

**Response Body** (url-encoded)
```
{"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_ship_id":[-1,16,4,631,40,841,1962],"api_clear_result":2,"api_get_exp":100,"api_member_lv":101,"api_member_exp":1836520,"api_get_ship_exp":[420,280,280,280,280,280],"api_get_exp_lvup":[[238307,245900],[190800,195800],[192751,195800],[177715,181500],[178788,181500],[50650,52800]],"api_maparea_name":"\u5357\u65b9\u6d77\u57df","api_detail":"\u6c34\u96f7\u6226\u968a\u306b\u30c9\u30e9\u30e0\u7f36(\u8f38\u9001\u7528)\u3092\u53ef\u80fd\u306a\u9650\u308a\u6e80\u8f09\u3057\u3001\u5357\u65b9\u9f20\u8f38\u9001\u4f5c\u6226\u3092\u7d9a\u884c\u305b\u3088\uff01","api_quest_name":"\u6771\u4eac\u6025\u884c(\u5f10)","api_quest_level":8,"api_get_material":[630,0,300,0],"api_useitem_flag":[0,0]}}
```

**Comment by nicky008** [comment]
Ah, I see... I think we still be missing somethings needed for it (KCDB) to check the backdoor from our platform (PC).

So I wondered why I was using the normal Twiter token and it didn't get the 400 error code response if it checked mine and allowed my PC to send the data back.

**Comment by dragonjet** [comment]
@nicky008 what client are you using to send the request?

**Comment by nicky008** [comment]
Hmm I used both the official KCDBPost for Windows and it's (KCDB) Twitter authentication and no any errors found.

Only when I found the 400 error is when I didn't login (did being anonymous) and tried to use it. I think it might need "your member authentication" to use (or able to read/send data from) it or any special cases from the owner.

**Comment by tasetase** [comment]
Can you link to the KCDBPost you're using ?

**Comment by nicky008** [comment]
@tasetase I use this version, 1.7.2.0...

http://kancolle-db.net/KanColleDbPost_1720.zip

Edit: I found something very important...
@dragonjet Have you try this Agent `6nENnnGzRgSTVeuU652r` yet? I think this is the Client Agent key of KCDBPost.

**Comment by tasetase** [comment]
Using agent=6nENnnGzRgSTVeuU652r works.

**Comment by nicky008** [comment]
:thumbsup:

**Comment by tasetase** [comment]
No news from kancolle-db from what I see, sadly.

**Comment by nicky008** [comment]
The owner might being busy on E-8 for now, mightn't he? :3

**Comment by NicolaosGreene** [comment]
I can relate somewhat, just finished E-7 before the reset

**Comment by nekoworkshop** [comment]
Woke up by my phone but got some good news.

The author of kancolle-db contacted me saying he would give us an agent key so that we can implement our own code to submit data to the DB. I've replied him and now waiting for his response. Hope when I wake up tomorrow I would have the green light.

Sorry for any typo or weird line breaks. I'm typing on my phone.

**Comment by dragonjet** [comment]
oh nice thanx :)

now to figure out how to make that call XD

last time I tried submitting got a `400 bad request` even with agent keys that worked with everyone else, but it was through **Dev HTTP Client**, another Chrome extension, not from KC3kai

**Comment by nekoworkshop** [comment]
Voilà! Here is the agent key for us `K2r3QgrKmBeNeDpzNey8`. I'll start working on it right away.

**Comment by dragonjet** [comment]
oh nice! good work @nekoworkshop :+1:

**Comment by nekoworkshop** [comment]
Update: Just submitted some data successfully with KC3Kai. a3b992cc6f12db5d28c950386de7d2ab21e9cfb9 
Needs complete error handling and input verification for API keys. Also contacted the author see if he has suggestion.

Sidenote: status code 400 usually means malformed payload while 403 and 502 (probably also 400 but I havn't seen any) are randomly popped up when sending with invalid token.

@dragonjet I ran into the same problem as you and it turned out that they were expecting URIencoded requestbody while others in plain text in the payload. 

![image](https://cloud.githubusercontent.com/assets/1346257/9839117/5ab64242-5a3d-11e5-9e87-0575fdc35661.png)

**Comment by dragonjet** [comment]
oh "**request body**", lol I included the request headers in my tests

**Comment by nekoworkshop** [comment]
Contacted the author today and he kindly added the required response header `Access-Control-Allow-Origin`. Now everything works smoothly.

**Comment by dragonjet** [comment]
:+1: :+1:  4 thumbs up including toes :+1: :+1:

**Comment by nekoworkshop** [comment]
Side note:
Document by Google https://developer.chrome.com/extensions/xhr is missing several important points.
1. Adding permissions in manifest only works when there **exist** an `Access-Control-Allow-Origin` in response header. In case the server doesn't return `Access-Control-Allow-Origin` at all, you're doomed. ( Spent hours trying to figure out what I did wrong and this is my best guess.)
2.`content_security_policy` behaves differently in packed extension compared to unpacked extension. I ran into a few errors in packed version of my build. Will look into them later.

**Comment by dragonjet** [comment]
whoops, this isn't merged to master yet right? so master is still safe for webstore release later?

**Comment by nekoworkshop** [comment]
@dragonjet  Nope. I'll test my branch for a few days, send some data to the DB and confirm with the author that everything is alright. After that I'll see when to merge it to the master branch so that other people on dev build can test it out.

BTW have you considered making a test branch ? At the moment the only way to release a feature to our develops and testers for testing are by merging it into the master branch but if someone merge a few commits into master one day before webstore release, those commits will be released to the public without being tested extensively. Just like my case, I would like to let other devs and testers try out my code but I have to wait until tomorrow because I don't want my code get to the master branch and released to the public...

By having a seperate branch we can keep merging our code into the test branch for testing without worrying about releasing untested code too early to the public since we'll only merge solid tested code to the master branch.

Just my two cents. To me we seems to be releasing new codes (features and bugfixes) a little bit too quickly. But please bear in mind that I'm still a student with little experience and I'm known to my friends for being shy and lack of confidence so... Anyway you guys are much more experienced than me ( This is even the first time for me to use github in real action...) and I'm willing to learn anything I can from you. Please feel free to point out anything I've gotten wrong.

**Comment by dragonjet** [comment]
hm right now I'm just using `webstore` branch. kind of opposite of that suggestion. when master looks fine, merge that stable into `webstore`. So if anyone pushes untested code into `master` after that, it won't be included in the release.

We could go from there, and when we merge into `webstore` that could be our test branch, and instead of the usual, "master is ok, merge to webstore, and release", we could then go "merge to webstore whenever, but test for a week before release". While that happens, master again gets filled with untested code. and will start a new cycle.

**Comment by nekoworkshop** [comment]
@dragonjet  So If I understand you right it works like this way ?

Developers work on and push commits to `master` branch whenever possible. Developers can also push commits to webstore branch for beta testing whenever we saw fit but any commits have to stay in the `webstore` branch for at lease a week before release. In other words, one week before the release the `webstore` branch will stop taking commits since any commits merged after that point will be ill-tested.

**Comment by dragonjet** [comment]
ah not atm, my second paragraph "*We could go from there*" is not yet in practice and is my way of adapting to your idea.

right now, all commits are either on feature branch or master, then I'm the only one to pull into webstore whenever we're doing releases

**Comment by nekoworkshop** [comment]
@KC3Kai/translators 
Dear translators. There are three setting entries to be translated for a new feature. They are above the panel setting section, near the end of the setting page.

You may refer to the following commit.
https://github.com/KC3Kai/kc3-translations/commit/692a528375a352ebdc4968204330012a49325e5e

**Comment by dragonjet** [comment]
I'll test this after the update, excited to see how it works :laughing:

**Comment by dragonjet** [comment]
![ss 2015-10-10 at 12 23 01](https://cloud.githubusercontent.com/assets/557312/10409003/c2c68894-6f49-11e5-98ad-d5d8ebd61c20.png)

yay!
