### ISSUE TITLE
Suggestion for expedition scorer

### ISSUE THREAD

**Issue by bcc32** [KC3Kai/KC3Kai#740]
Would it be possible to add support for buckets, flamethrowers, furniture coins, etc.?

(ref #301)

**Comment by Javran** [comment]
I could add them and actually was thinking about it, but I haven't found a good way.

* if I put them in resource priority, it'll be a big number to have a significant impact on results, and those resources are RNG based, which makes them not very reliable.

* an alternative solution is to ignore those resources but include them in the results. by doing so user might need to uncheck some expeditions(that keep showing up on top but don't have the desire resource) before getting a desired plan.

I'm open to suggestions about finding a better approach.

**Comment by c933103** [comment]
Statistical Expected Return? But that need to separate for GS or non GS case

**Comment by dragonjet** [comment]
I'm not much of a fan of the idea. One example is expedition 2, a 50-50 chance to get a bucket. What is the factor for scoring items in relation to priority, I mean I put all resource and bucket at priority 1. 

For a sample expedition
100 fuel score + 150 ammo score + 120 steel score + 40 bauxite score + (1 bucket score / 2)

bucket score is highly undervalued by default unless we add in a factor, and again divided by 2 since 50-50 chance. And we aren't even sure about all other expeditions, and as @c933103 mentioned about GS effects, a highly debated topic.

**Comment by nicky008** [comment]
I feel that GS or not GS matter is like 50-50 chance in getting bucket in exp.2, half of people think it should do for better planning and also half of people think it shouldn't do because of unreliable results and too complex in separating.

Still need more tests in score balancing and easier, simpler calculation (if you guys want GS).

**Comment by c933103** [comment]
GS or not do not affect chance of getting the first item (the item shown to the left), but is is 100% vs 15% for the second item (item shown to the right)

**Comment by LostLogia4** [comment]
Already tracked in Expedition History and Resource Ledger.
The probability effect makes the items implausible to be added in, so it'll be closed.
