### ISSUE TITLE
Battle prediction does't work on both legacy/natsuiro panel

### ISSUE THREAD

**Issue by Horadrimus** [KC3Kai/KC3Kai#775]
Hello,

was using 18.2 version earlier and battle prediction did not work at all.

after installing ver 19 from zip pack it still does't work in both panels

![battle prediction](https://cloud.githubusercontent.com/assets/13624520/9714724/decdd714-5594-11e5-95b8-afa796ca4a6b.png)

**Comment by ReiFan49** [comment]
i guess, it just fixed now as reported on #769 #770 #772

**Comment by ethrundr** [comment]
@dragonjet I think we should quickly releases this Battle Prediction bug-fix to the Webstore version, before more dupe reports coming in to the GitHub. As for why, this is the mostly used feature in KC3kai, and there is no way people won't notice and get confused about this bug. 

Up to this moment I already have numerous question (maybe more than 10, or even 20), asking why the prediction is not working from my local KC community. I think @ReiFan49 also know about this, since some even post it in group, asking for explanation there.

**Comment by bamboo3250** [comment]
yup, I also feel like we need a hot fix here. Those reports are coming.

**Comment by ethrundr** [comment]
Including mine, which is posted at the exact same time with @bamboo3250's, there are already 4 dupe reports.

I believe the counter will keep increasing if we don't do the hotfix soon.

**Comment by dragonjet** [comment]
hm I agree, alright will adjust the timer and give around 3 hours for people to get notified on the timers so they'll be well informed and not crash in-game
