### ISSUE TITLE
Notification Bug

### ISSUE THREAD

**Issue by RredderR** [KC3Kai/KC3Kai#787]
I don't get the usual exped/repair notification sometimes. But it doesn't happen that much. Although, it would be better if you would fix it so it won't happen anymore (y)

**Comment by freezebear** [comment]
Chrome Notification ? Better check your setting first... :v / 
![image](https://cloud.githubusercontent.com/assets/12047229/9750713/11f6fe4c-56ce-11e5-90e0-33f751e189b0.png)

**Comment by ethrundr** [comment]
The notification will NOT appear if your computer goes to sleep or standby condition. The notification requires active session in order to be working.

Whenever your computer goes to sleep or standby, all the notification happens during that time will be stacked when the next notification sounds.

Also, make sure you set your computer permission to allow pop-up notifications from KC3Kai to ensure the notification works perfectly. If you revoke this permission, undoubtedly the notification won't work :smile:

**Comment by RredderR** [comment]
@freezebear it's checked.. But I said that I don't receive notifications "SOMETIMES". Thanks for noticing though.

@ethrundr I know that I won't recieve notifications if my pc goes to sleep. I do get notifications even when I leave my pc alone (Even if the screen fades black :v). And my pc allwos notification from KC3Kai.

Srlsy, though. I said "SOMETIMES". So it MIGHT be a bug.

**Comment by ethrundr** [comment]
@RredderR instead using caps-lock for emphasize, you can use **bold** for it

as how to use it, just wrap the text you want to be bolded with double-asterisks:
`**<your bolded text goes here>**`, and the result **will be like this**

**Comment by dragonjet** [comment]
but during those times do you still hear the ding or pop sound?

**Comment by RredderR** [comment]
@dragonjet nope. I only hear the pop sound when the notification pops-up.

**Comment by RredderR** [comment]
@dragonjet Please close :P
