### ISSUE TITLE
Resupply Label

### ISSUE THREAD

**Issue by bcc32** [KC3Kai/KC3Kai#789]
Re: #719 the label was changed from "Need Resupply" to "<100% supply" in fc90d8a1.
It looks like it's a bit tight and may need some adjustment (probably OK to move the repair/morale/HP indicators a bit over to the right).

![screen shot 2015-09-08 at 17 45 34](https://cloud.githubusercontent.com/assets/1239097/9748380/489fb7c6-5652-11e5-998c-f33678e30098.png)

**Comment by dragonjet** [comment]
hm all of those 6 items are of the same width so that it will be uniform in all orientations, which iirc the vertical have 2 columns, 3 rows, adjusting individually will break other layouts. Might just think of another text

**Comment by ethrundr** [comment]
Like I said somewhere before, if possible why won't we let the user set their own supply threshold for the 1st fleet? I suggest this since not all people will resupply their ship even after 1 bar decrease when it comes to the 1st fleet.

For the 2nd to 4th fleet, we can leave as it is now, since expedition fleet need to be fully resupplied before can be sent again, so even one bar loss is necessary to be notified.

**Comment by dragonjet** [comment]
@ethrundr hm seems I misunderstood your previous suggestion. where's the last thread again? xD

**Comment by ethrundr** [comment]
@dragonjet the problem is... I forgot where as well XD

**Comment by ReiFan49** [comment]
lol i thought @bcc32 already pointed out on the issue starter about @ethrundr's issue....

**Comment by McDohl** [comment]
https://github.com/KC3Kai/KC3Kai/issues/719

**Comment by dragonjet** [comment]
aye see :laughing: you said to make it "< 100% supply" on #719

**Comment by ethrundr** [comment]
:laughing:

**Comment by dragonjet** [comment]
wait let me re-read I think I derped again on reading comprehension :v

**Comment by ethrundr** [comment]
After @ReiFan49's update:
![screen shot 2015-09-11 at 11 40 55](https://cloud.githubusercontent.com/assets/13522800/9805982/52a1fdfe-587a-11e5-9071-47aa03528670.png)

When the supply status is above threshold, I suggest it display different color, let's say, in orange.
The cross mark also might as well be changed, but not green tick as well.

As for why, even though the supply for the fleet is below 100%, it is still above the configured threshold, so appropriately we don't show a red warning label, rather only a notification that the fleet might need resupply, supposedly in yellow or orange.

Also, for the expedition fleet (Fleet 2, 3, 4), no matter what the threshold is, when their supply is lowered even by 1 bar, the resupply warning should be shown, since expedition won't succeed when the fleet is not fully supplied.

**Comment by ReiFan49** [comment]
the first focus of these is on sortie warning, to tell that the sortie is overdone (4+ nodes)
nah, for expedition one... must not on sortie, have a <100%, and put the `alert_supply_exped` on (default: on, focusing on this) will have quicker warning regardless the supply minimun input.

**Comment by dragonjet** [comment]
hm so far as I understand it, these are the stuffs?

:black_medium_square: Do not update resupply status for first fleet until Home Port
:black_medium_square: Update resupply status for first fleet if less than threshold
:black_medium_square: Keep status for Fleet 2,3,4 which shows warning as long as not 100%

**Comment by ethrundr** [comment]
@dragonjet more or less, yep, it's like that

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9806854/a2f51346-5874-11e5-938b-12a5aca4b0f4.png)
but i did not want this to be happen ._.)

**Comment by ethrundr** [comment]
It's your fault sortieing with 3rd fleet XD

**Comment by nicky008** [comment]
It can't be helped. :relieved:

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9806937/f1ab1dcc-5875-11e5-8f16-a1fa7a24e33f.png)
done it.

**Comment by ReiFan49** [comment]
gonna fix supply marker for first fleet

**Comment by ethrundr** [comment]
all that left is to raise the threshold limitation from 50% to 90%...

**Comment by ReiFan49** [comment]
threshold changed from `0 to 5` bars
to `0 to N` bars, with limit of length `1` char

**Comment by ethrundr** [comment]
Gotta pull and try this~
