### ISSUE TITLE
About morale notification

### ISSUE THREAD

**Issue by JD-Kurotoshigami** [KC3Kai/KC3Kai#797]
I have a suggestion on the morale notifications(?)
Red Face = "Fatigued"
Orange Face = "Tired"
Morale < 40 = "Low Morale"
Morale 41 - 49 = "Normal"
Morale 50 - 53(or 54?) = "High Morale"
Morale 54(or55) + = "Happy"
 
![image](https://cloud.githubusercontent.com/assets/13150941/9759400/a68c54a4-5727-11e5-88d4-f2638a7231fb.png)

**Comment by ethrundr** [comment]
The morale grouping is:
0-22: Severely Fatigued
22-32: Moderately Fatigued
33-40: Slightly Fatigued
41-49: Normal
50-52: High Morale (no Sortie boost)
53-100: High Morale (with Sortie boost)

For the notification itself, we use that as the regen time indicator rather than notification, so it's quite not necessary. While for the individual ship, they already have their own morale counter.

**Comment by McDohl** [comment]
actually its like this
99~53 High Morale	
[Sortie] Higher evasion and accuracy during battle
[Expedition] Higher chance of great success in expedition
[Expedition] Higher chance of triggering support expedition
52~50 High Morale	
[Sortie] No effect on performance
[Expedition] Higher chance of great success in expedition
[Expedition] Higher chance of triggering support expedition
49~40 Normal	
Normal state - no effect on performance/special effect
39~33 Slightly Fatigued	
[Sortie] No effect on performance
[Expedition] Expedition will fail if your fleet returned in this state
32~23 Moderately Fatigued	
[Sortie] Decreased evasion and accuracy
[Expedition] Expedition will fail if your fleet returned in this state
22~0 Seriously Fatigued	
[Sortie] Severely decreases evasion and accuracy
[Expedition] Expedition will fail if your fleet returned in this state

**Comment by dragonjet** [comment]
@JD-Kurotoshigami do you mean the icon to be changed to faces instead of check and cross?

**Comment by JD-Kurotoshigami** [comment]
@dragonjet thats ok too :)

**Comment by nicky008** [comment]
+1 Nice...

**Comment by nekoworkshop** [comment]
How about some colored arrows.
![image](https://cloud.githubusercontent.com/assets/1346257/9829138/9282a14c-58c7-11e5-8f1d-5452f8e65f97.png)

**Comment by ethrundr** [comment]
and now for which morale each arrow used for? :laughing: 
however, personally I'd rather choose the in-game faces emoji...

ps: please change the < 10 morale into Travis-kun faces, so he won't get angry with this :laughing:

**Comment by nicky008** [comment]
@ethrundr and dat pink emoji also, right? :laughing:

**Comment by ethrundr** [comment]
@nicky008 sure :laughing: 
make it appear when ship's morale is > 85 and she is above Lv100~

**Comment by dragonjet** [comment]
i havent seen a pink emoji before, but I have seen it in my ripped files, what was it for?

**Comment by nicky008** [comment]
@dragonjet Rumor about it is still debatable until today, you know.

**Comment by ethrundr** [comment]
No one ever know what is it used for, up to today....

**Comment by dragonjet** [comment]
Now converted to face icons instead of check-cross

Icons will follow real morale values, and disregards the minimum value on settings
(minimum value on settings still apply on the text and its coloring)

* >49 yellow
* >39 white
* >19 orange
* etc red

![ss 2015-09-14 at 11 08 05](https://cloud.githubusercontent.com/assets/557312/9853304/7bb12f0e-5b35-11e5-9a9a-0e37c7b0b41c.jpg)
