### ISSUE TITLE
[Suggestion] Node Differentiation 

### ISSUE THREAD

**Issue by JD-Kurotoshigami** [KC3Kai/KC3Kai#798]
why not differentiate the submarine nodes and airfight nodes from normal battle nodes?
by this I mean in the battle info and sortie history
example : normal nodes are red circles while the submarine/air fight nodes have either different colors, different figure, or both

**Comment by ethrundr** [comment]
Simple answer:
Submarine node still shows as normal battle node, despite some has a SS sprite beside
while Aerial node has a completely different shape and color, indicating that its has completely different battling method.

While personally I'm not in favor for the Submarine node, it is quite necessary to give different coloring for the aerial node, since this already a whole different node. For the color itself, we can use a circle with shade from red to blue, since Aerial node has red and blue arrows.

**Comment by dragonjet** [comment]
tbh there's no difference in game data IIRC CMIIW, both have the same `api_event_kind`?? which means we cannot differentiate nodes :sob:

**Comment by Javran** [comment]
closing this: now we have the screen overlay feature that mark nodes with, letter, resource, boss icon and whatnot manually, which should be good enough.
