### ISSUE TITLE
i installed the latest version and now i cant see my team info

### ISSUE THREAD

**Issue by ikev-n** [KC3Kai/KC3Kai#838]
help... i removed the kc3 tool and re downloaded it from the chrome store and still the same

**Comment by nekoworkshop** [comment]
@ikev-n  By saying "team info" do you mean this panel ?

![image](https://cloud.githubusercontent.com/assets/1346257/9826269/e6806a16-58a6-11e5-972f-d1e06daf5ba4.png)

**Comment by ikev-n** [comment]
Like my fleet... It doesn't show my team's health bar or if I make a new ship

**Comment by happyh0rse** [comment]
@ikev-n I'm having the same issue as per #826.

Using the latest version (19.2). The previous version (19.1) seems to be working fine...

**Comment by ikev-n** [comment]
Exactly! I hope they can fix it...

**Comment by dragonjet** [comment]
will continue on #826

**Comment by ethrundr** [comment]
@happyh0rse regarding quest update, it usually happen when your panel is unable to communicate either with your local database or with your strategy panel. It'll produce a "Runtine Exception Error", thus rendering the extension inoperable. This error usually happens when you start your panel late, or reload it mid-game, which both has chance to make the database connection crashes.

Next time the quest bug (not-updated quest tracking), I suggest to try reloading everything:
- Close all active window relating to the KC3kai: API/Webgame, Admiral Panel, Strategy Room, Settings
- Open chrome://extensions, and enable Developer Mode
- Then press Ctrl+R (or Cmd+R in OS X platform)
- Reload all the window once again, starting by clicking "Play via API Link" or "Play on DMM Website" from the extension menu, regarding which one you'd like.

If this attempt still not fix the bug, you may need to relaunch your whole Google Chrome and repeat the steps above. However, if problem persist after relaunching the Google Chrome, please let us know, since at this case now, it has high chance that we derped on the code :smile:
