### ISSUE TITLE
[Suggestion]Modding Feature?

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#847]
i.e. If we have the feature and user turn the feature on, the software should be able to store caches into amother folder which user can access it. And it will check if the folder include the required files before the game request it from server. If those swf are found in cache, then it would check is it is the latest version, and if it is true, then it will load the swf from cache folder instead of game server. It enable the use of prepackaged cache files, as well as insertion of third party images in to the game.

Just like what https://github.com/df32/KanColleCacher this KCV plugin did.

As per the reason why kc3 kai only translate quest but not other part of the game, this function may not be desired for the same reason. Howeber there're already in-page refresh function in KC3 Kai which have been marked as dangerous so it can possibly be treated in same way?

**Comment by dragonjet** [comment]
hm theoretically this is possible.

By using [`chrome.webRequest.onBeforeRequest`](https://developer.chrome.com/extensions/webRequest#event-onBeforeRequest), we can stop the swf request to the server, and "redirect" it to a local file. The thing to note is "redirect", because we cannot modify responses, not just by our policy, but by chrome technical limitations. I guess redirecting assets to a local file wouldn't be harmful.

tbh when I saw that on KanColleCacher, I thought about this and actually creating a separate "black KC3" release with dangerous features such as this :v

**Comment by LostLogia4** [comment]
May I test the caching feature? I kinda missed Murasame's swimsuit there...

**Comment by dragonjet** [comment]
no active development on this yet. but i'd like to try one of these days just to test the feasibility

**Comment by c933103** [comment]
https://github.com/Provissy/HoppoPlugin This multi-functional multi-lingual KCV plugin that also include the same feature might help.

**Comment by dragonjet** [comment]
As explained further in #1516, we will not implement client-side modification
