### ISSUE TITLE
[Subtitles] Add the functionality to translate the info earlier.

### ISSUE THREAD

**Issue by kololz** [KC3Kai/KC3Kai#860]
Stated above. We'd like to translate these subtitles earlier before getting to real release ;)
By the way, I wanna know about how 0.5 sec for each character works.
It uses Japanese version or the translated version of the subtitle?

**Comment by dragonjet** [comment]
the duration uses the translated one. unfortunately we also don't have a copy of the japanese text in

**Comment by nekoworkshop** [comment]
@dragonjet Ever thought about reading the length of mp3 and use it as the duration ?

**Comment by SerialConvort** [comment]
I agree with Neko, using the length of the Mp3 as the duration is efficient imo

**Comment by dragonjet** [comment]
hm that's actually a good idea, let me try that

**Comment by dragonjet** [comment]
tried it, and becomes an infinite loop
```
subtitleMp3 = new Audio();
subtitleMp3.canplaythrough = function() { 
	console.log("DURATION: "+subtitleMp3.duration);
};
subtitleMp3.src = request.url;
```
The problem is that tagging the mp3 file into an audio object, will request it again from the server, thus firing the `Network.js` listener to sound files, and thus starting another loop.

I can move this to `Service.js` where it will determine the audio duration first before giving to the game screen, but I thought this will mean double network load for the user, unless cached. I'm a bit concerned of memory usage, and network bandwidth doubling

I will still try to move this to `Service.js` though. I'll monitor if the memory usage is affected, and if the request log has a "*(from cache)*" indicator

**Comment by dragonjet** [comment]
seems it doesn't use the game cache, and instead have its own. we don't wanna double the network for the user so I'm not gonna continue using a "re-load mp3 file to get duration" mechanic.

![requests](https://cloud.githubusercontent.com/assets/557312/9839857/86a7013c-5ab7-11e5-822d-acbea2778123.jpg)

If only there's a way to get hold of the file loaded on the game network :sob: I guess the option now is `Content-Length` or if anybody else has an idea?

**Comment by ReiFan49** [comment]
i think that content-length is enough to guess it, (even we know content-length itself is whole the network data length)

**Comment by c933103** [comment]
@kololz When you said "translate these subtitles earlier", did you mean writing translation of kanmusu lines into files in kc3k translation repo ahead of the functionality itself being made available?

**Comment by kololz** [comment]
@c933103 Since the translation format is the same everywhere, it doesn't matter where. Just copy the whole content to KC3Kai translation repo when we officially release subtitles.

**Comment by dragonjet** [comment]
@KC3Kai/translators can now add subtitle translations to the TL repo, where you can use EN as basis:
https://github.com/KC3Kai/kc3-translations/tree/master/data/en
see `quotes.json`
