### ISSUE TITLE
OSAPI?

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#890]
I heard that except the regular API link, there are also a type of api link called as OSAPI link which have shorter lifespan and thus more secure. How about adding an option to fretch and play with osapi?

**Comment by dragonjet** [comment]
osapi is an iframe embedded on the DMM play page, so the hierarchy of embedding is
```
+------- DMM -------+
|   +---osapi----+  |
|   |  api_link  |  |
|   +------------+  |
+-------------------+
```
back then, we use these on other DMM games that do not have API link.

we could probably use this as well but since it is short-lived (usually just single session and lasts for an hour or two), I doubt anyone would use this versus API link, and just play on DMM website itself it they want a quick game.

unless the reason is that, they don't want DMM layout and prefer the 800x480 frame without using the API link.

**Comment by c933103** [comment]
an hour or two still slightly longer than the current ordinary api link lifespan fwiw...
