### ISSUE TITLE
Repair Timer calculation goes foward

### ISSUE THREAD

**Issue by MichadelCS17** [KC3Kai/KC3Kai#891]
When I looked the repair timer, it doesn't reduce, but increase...... sorry for my bad english

**Comment by LostLogia4** [comment]
When words can't describe your problem, you should post a screenshot instead.

**Comment by ReiFan49** [comment]
basically you toggled the "estimated repair timer ends" one.
for example, your time is 12:12:12, and have 3 ships with variable repair time,
let's say...
```
Ship#  RepairTime   Estimated
ShipA    03:10:00    15:22:12
ShipC    00:00:45    12:12:57
ShipF    40:00:00    04:12:12+
```
the longest estimated time will be shown on the fleet, which is 04:12:12 in a red color (because 24+ hours of estimation)
if you quickly repair it with bucket, the ShipF counter will be ignored, and it'll follows the next longest one, which is ShipA, which have 15:22:12, assuming you've done it in under a second.

the time ticks, so does the estimated time one, if you take 8 seconds to quick repair ShipF, it means the repair time will be
```
Ship#  RepairTime   Estimated
ShipA    03:10:00    15:22:20
ShipC    00:00:45    12:13:05
```

**Comment by dragonjet** [comment]
I think that he meant was,

* 00:00:10
* 00:00:10
* 00:00:10
