### ISSUE TITLE
[Feature] Display Base EXP for PvP in Activity Tab

### ISSUE THREAD

**Issue by LostLogia4** [KC3Kai/KC3Kai#904]
Just asking, is there anyone here who would like to have the base EXP from PvP displayed in Activity tab? As an optional notification of course...

<s>Also, include the enemy PvP threat level below it based on number of heavy hitters and potential air power.
Better yet, put it in Battle Tab and temporarily rename it as "Scout" until api_practice is called.</s>

**Comment by ethrundr** [comment]
Rather than put the base EXP from PvP in the Activity tab, why won't we instead implement the PvP logging history on the Strategy Room. On there, we'll store the base EXP of each PvP encountered.

Anyway, sorry for being away for a month :joy:
Was focusing on the rank, and in the end I able to finish in rank 352 with 1,991 points total :laughing:

**Comment by LostLogia4** [comment]
You don't say. I finished at 139th place with 2169 points.
Could've reached top 100 is I go all out... which I don't...

**Comment by ethrundr** [comment]
well in last week I'm facing with ammo shortage, as well as big event here in Indonesia...
so, yeah, this the best I can do this month, even though I can do passed top100 if doesn't facing with the resource shortage.

**Comment by LostLogia4** [comment]
ah, ammunition... I've spent around 20-30k for 5-5 alone, plus I've spent over 60k bauxite throughout the month... I really wonder how the toplisters could keep up the sorties...

**Comment by Nya-chan** [comment]
This has now been implemented, can be closed.

**Comment by sinsinpub** [comment]
Close by #1765
