### ISSUE TITLE
Has anyone considered migrating KC3Kai from extension to Chrome packaged apps ?

### ISSUE THREAD

**Issue by nekoworkshop** [KC3Kai/KC3Kai#913]
Yesterday I exchanged some words with Javran about a few features we had in mind and during my quick search I realized Google are keeping the most powerful APIs exclusively available to package apps. Such as this one.

https://developer.chrome.com/apps/sockets_tcp

I know we're still waiting for the abilities to read and modify request bodys from WebRequest APIs. Although at the moment I have no idea what we can achieve with that but I guess the possiblity to use raw sockets might worth a look ?

**Comment by nekoworkshop** [comment]
Sorry for the typo... Not a good idea to open issue before I go to bed.

**Comment by ethrundr** [comment]
What the difference between extension and packaged apps?
Even though my major is IT, to be honest I still don't quite understand the difference between these two.

**Comment by dragonjet** [comment]
though I've been looking at apps for sometime now, usually when I was first starting, and looking for chrome docs, I sometimes mistake an API to be app-only vs extension-only so I grew aware between both. At times, I do even check if porting is possible, and I scrapped the idea losing the ability to read network requests, (*except for remote debugging done by [KanColle Launcher (KCIC)](https://chrome.google.com/webstore/detail/kancolle-information-cent/cmgnconifcfminmeikodmnlcpickfhfk)*)

I doubt we can use the `sockets_tcp` for it, since I don't think it intercepts, but only creates and receives requests to and from the app itself, and not evesdropping from another flash client.

**Comment by dragonjet** [comment]
wont fix for now, chrome apps still have no eavesdropping mechanism. should re-open if there are any leads for new chrome APIs
