### ISSUE TITLE
Unable to enter user info when trying to play via DMM on Frame

### ISSUE THREAD

**Issue by Byakushiki** [KC3Kai/KC3Kai#942]
I am trying to play via Frame and when the page goes to the DMM login page, I am unable to enter my user info. Basically what happens is when I click on the text field for username, the cursor to enter text appears but then disappears instantly. Same thing goes for the password field. I am able to click on the different links on the page as well as the check boxes, but I can't enter anything into the text fields. I also tried "Start Game Anyway" and the same thing regardless happens. Here's a video of what I mean: https://www.youtube.com/watch?v=Tc67JQVb67o&feature=youtu.be

**Comment by ethrundr** [comment]
are you trying to logging in?
if yes, please use the original DMM direct (on the website).

even though direct and frame basically is the same, but for login process it'll be better if you access the full website rather than the "cropped" one in the frame mode.

**Comment by Byakushiki** [comment]
I am able to play directly on DMM, but I like the frame better so I dont have to see the ads and stuff on the sides. Thanks though!

**Comment by dragonjet** [comment]
This is true, the viewer is taking the focus away from the game every second, so that when you press hotkeys such as <kbd>F5</kbd> (refresh), <kbd>F9</kbd> (screenshot) or <kbd>F10</kbd> (clear overlays), it will recognize your keypress.

This is because pressing these hotkeys naturally will not work and is captured by the game client (flash), not the browser.

The work around is to type if onto notepad, then copy, then click on the text field, *then quickly* paste. The re-focus happens every second.

**Comment by Byakushiki** [comment]
The other work around would to be to login into DMM from outside of KC3 Kai and then do the frame method from there, or at least that is how it worked for me.

**Comment by LostLogia4** [comment]
@dragonjet
That workaround you suggested is simply untenable when I'm playing in computer lab or cybercafe, unfortunately...

**Comment by dragonjet** [comment]
that's one of two suggestions. when people do report this, it is always mentioned the two requirements for DMM frame would be to be already logged in and language set to JP, which as @Byakushiki  said to login separately on another tab

but for other text input like admiral comment and fleet names, then right now, as it's not yet fixed, would be to do the copy-paste

**Comment by LostLogia4** [comment]
Is it possible to toggle the option so that the de-focus can be temporarily lifted?

**Comment by Byakushiki** [comment]
I dont know much programming but I would suggest something along the lines of the game auto-focus and framimg being activated only when the flash window for Kancolle pops up.

**Comment by dragonjet** [comment]
@Byakushiki ah best thing I heard all day. It is possible to only start taking keyboard focus only after game start. Though this will not fix renaming fleets, etc.

What @LostLogia4 would suffice, possibly, pressing <kbd>F7</kbd> to toggle key focus. Though the problem is re-enabling it back. Basically pressing <kbd>F7</kbd> after focusing keys for the game will not be detected by us.

**Comment by LostLogia4** [comment]
And we already have a crowded Admiral panel already... I sure made a brilliant idea here.

**Comment by c933103** [comment]
Is that admiral comment/fleet name/first login part fix-able? As I heard
that's something you inherently can't modify if you are using api link
2015/10/14 18:55 "Jet Rico" <notifications@github.com>:

**Comment by Byakushiki** [comment]
@c933103 the iframe isnt just the api as far as I know though. Its the actual flash from the kancolle dmm page, just that kc3 Kai frames the entire page just to show kancolle and nothing else. Essentially a crop of the entire page if that makes sense.

**Comment by dragonjet** [comment]
yes @Byakushiki is right, DMM Frame definitely could do the name changes, it's just that the keystrokes are stolen

**Comment by dragonjet** [comment]
Pressing <kbd>F7</kbd> will now let you input into textfields for both DMM login page and the game texts such as fleet names and admiral comment. The key allowance is 20 seconds and will have a time bar at the bottom of the screen. After this time, the key strokes will then be captured again by the viewer instead of the game.
