### ISSUE TITLE
Alert when heavily damaged

### ISSUE THREAD

**Issue by Aggresivesnakes** [KC3Kai/KC3Kai#954]
There should be an alert when a ship in your fleet is heavily damaged.

**Comment by bcc32** [comment]
Wait, do you mean like alert()?  i.e., a pop-up message?  That'd be cool.

**Comment by LostLogia4** [comment]
Pretty sure that this has been requested since forever.

**Comment by dragonjet** [comment]
yes even on gitter, but uh. I don't get why one would not look at the fleet info before proceeding to next node XD we even have combined fleet mode to see 1 and 2 without clicking

**Comment by c933103** [comment]
For instance when you are fishing for 100 rounds in 1-5-A and still ongoing
after working for 20 hours and you are sick then your brain would not be
processing anything aside from clicking mouses. Thus if something taiha you
would need an alert to wake your brain up.
2015/10/18 10:40 "Jet Rico" <notifications@github.com>:

**Comment by bcc32** [comment]
We could make it an option in the settings menu.

**Comment by dragonjet** [comment]
alrighty, here we go.
complete with blur + on-screen blood + heartbeat sound effect

I call it on settings the *"Annoying Taiha Alert*" (disabled by default)

![dragonjet 2015-10-18 22-14-43 54](https://cloud.githubusercontent.com/assets/557312/10564411/dfbd05fc-75e5-11e5-91a2-c2c4ca4bdb9e.jpg)

**Comment by c933103** [comment]
The reason why I think something like http://rr.img.naver.jp/mig?src=http%3A%2F%2Fimgcc.naver.jp%2Fkaze%2Fmission%2FUSER%2F20140408%2F27%2F2656807%2F9%2F800x480x180749863841924d89f047af.jpg%2F300%2F600&twidth=300&theight=600&qlt=80&res_format=jpg&op=r is still better than this notification is that, 1. Player have to change their routine mechanical behavior to dismiss this notice in order to sortie with taiha, it should able to wake people up without being annoying and work well with sound disabled, 2. when you sortie to 1-6 and go taiha toward base, you don't need to keep having the alert on.
