### ISSUE TITLE
[Suggestion] Taiha Alert

### ISSUE THREAD

**Issue by RredderR** [KC3Kai/KC3Kai#957]
Instead of having blur + blood splatter + heartbeat sound effect when there is a taiha (regardless if flagship, regardless if has damecon), why not blur + screen cracks + heartbeat sound effecr when there is a taiha. It would look more appropriate because they're ships.. And girls, at the same time. To much blood makes the game more gore-like. Also, the blur effect should start when a shipgirl gets chuuha.

**Comment by dragonjet** [comment]
Inspiration was from FPS games though. Even local friends suggested the MGS alert sound ir just simple siren, but in the end went with this.

It was also hinted by one of friends to be halloween bonus, since the next update is October 30, perfect timing for this small gory feature.

Enhancements to this might be added in the future though with the ability to toggle blur, select blood or crack effects, or toggle the sound. But it's still a "might", higher possibility is that it'll be left as it is unless there's a community uproar.
